#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev-srv/user -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It manages dev server users

main() {
    cd /tmp
    local data='@@host@@/dev-srv/user/~data'

    # create dev user
    echo 'Adding dev server user "'$_dev_user_name'"...'
    sudo useradd -s /usr/sbin/nologin -rUm "$_dev_user_name" 2&>1 /dev/null || true
    # add user to the sFTP group
    sudo usermod -aG sftp-only $_dev_user_name

    # disable password access
    sudo usermod -p '*' $_dev_user_name

    # create dev www user
    local dev_www_user_name=$_dev_user_name'-www-data'
    echo 'Adding dev server www user "'$dev_www_user_name'"...'
    sudo useradd -s /usr/sbin/nologin -d /nonexistent -rUM $dev_www_user_name 2&>1 /dev/null || true
    # add www user to the www-data group
    sudo usermod -aG www-data $_dev_user_name

    # create dev user sFTP work directory
    local dev_user_work_dir='/sftp/'$_dev_user_name'/work'
    echo 'Creating dev user sFTP work directory "'$dev_user_work_dir'"...'
    sudo mkdir -p $dev_user_work_dir
    sudo chown $_dev_user_name':'$_dev_user_name $dev_user_work_dir

    # setup dev user web environment
    local dir=/srv/dev/public
    sudo mkdir -p $dir'/'$_dev_user_name

    # setup dev user work environment
    local dir=/srv/dev/users
    sudo mkdir -p $dir'/'$_dev_user_name'/work'
    sudo mkdir -p $dir'/'$_dev_user_name'/tmp'

    # php-fpm.conf setup
    local src='/srv/dev/users/example/php-fpm.conf'
    local dest='/srv/dev/users/'$_dev_user_name'/php-fpm.conf'
    if [[ ! -f $dest ]]; then
        echo "$(wget $data$src -qO- | \
            sed s/'%NAME%'/$_dev_user_name/g)" | \
        sudo tee $dest > /dev/null
    fi

    # vhost.conf setup
    local src='/srv/dev/users/example/vhost.conf'
    local dest='/srv/dev/users/'$_dev_user_name'/vhost.conf'
    if [[ ! -f $dest ]]; then
        echo "$(wget $data$src -qO- | \
            sed s/'%NAME%'/$_dev_user_name/g)" | \
        sudo tee $dest > /dev/null
    fi

    # setup database account
    # TODO create random password
    echo 'Creating MySQL client user...'
    sudo -i mysql -e "CREATE USER '$_dev_user_name'@'localhost' IDENTIFIED BY '123456';" 2&>1 > /dev/null || true
    sudo -i mysql -e "$(wget $data/extra/mysql-grant-client.sql -qO- | sed s/'%USER%'/$_dev_user_name/g)" 2&>1 > /dev/null || true
    #sudo -i mysql -e "$(wget $data/extra/mysql-grant-client.sql -qO- | sed s/'%USER%'/$_dev_user_name/g)"

    # TODO read dev user SSH public key

    sudo service sshd restart

    # restart PHP-FPM & apache
    load php/utils
    load apache/utils
    php_fpm_restart
    apache_restart
}

main "$@"
