#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev-srv/user -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It manages dev server users

main() {
    echo -e "\nDev server user setup..."

    #------+
    # init |
    #------+
    load dev-srv/user/arguments "$@"

    #-------+
    # setup |
    #-------+
    load dev-srv/user/add

    #------+
    # done |
    #------+
    echo 'Dev server user setup done...'
}

main "$@"
