#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs ChromeDriver for Selenium

main() {
    cd /tmp
    local lock=webino.sw.chrome.driver.lock

    if [[ ! -f $lock ]]; then
        echo "Installing ChromeDriver for Selenium..."

        # resolve latest chrome driver version
        chrome_driver_version_latest=$(echo $(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE))

        # chrome driver
        local file=chromedriver_linux64.zip
        local path=/tmp/$name
        wget -N 'http://chromedriver.storage.googleapis.com/'$chrome_driver_version_latest'/'$file -P /tmp \
             && unzip $path -d /tmp && rm -f $path & spinner $! 2>&1

        chmod +x /tmp/chromedriver
        sudo mv -f /tmp/chromedriver /usr/bin/chromedriver

        touch $lock
    else
        echo 'ChromeDriver for Selenium already installed...'
    fi
}

main
