#!/bin/bash

# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# PHP-FPM script

help () {
    echo ''
    echo ' Usage:'
    echo ''
    echo ''$BASH_SOURCE' start|stop'
    echo ''
}

# Commands

case "${1:-''}" in
    'start')
        echo "Starting php-fpm..."
        %bin-prefix%php-fpm -y %conf-prefix%etc/php-fpm.conf -c %ini-prefix%/etc/php.ini
        exit 0
    ;;
    'stop')
        # Kill all php-fpm instances
        echo "Stopping php-fpm..."
        kill $(ps aux | grep '[p]hp-fpm' | awk '{print $2}') 2> /dev/null
        exit 0
    ;;
    *)
        help
        exit 1
    shift
esac
