#!/bin/sh

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/os -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04

wget @@host@@/os/setup -qO- | bash -s -- "$@"
