#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It resolves host OS info

main() {
    # resolve server info
    if [[ -z $host_name && (-n $env_dev || -n $env_pub) ]]; then
        # (dev|pub only)
        echo 'Resolving host info...'
        host_ip=$(ip route get 8.8.8.8 | awk '{print $NF; exit}')
        host_name=$(cat /etc/hosts | grep $host_ip | awk -F' ' '{print $2}' | awk '{print $1}' | tr . -)
    fi

    # server info defaults
    if [[ -z $host_name ]]; then
        echo 'Using default host info...'
        host_name=webino.local
    fi

    # sysadmin mail default
    admin_mail=${admin_mail-'admin@'$host_name}

    # show host info
    echo 'Host IP: '$host_ip
    echo 'Host name: '$host_name
    echo 'Admin mail: '$admin_mail
    echo ''
}

main
