#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It fixes locale

main() {
    # exit early on clean
    [[ -n $clean ]] && return


    local lock=/tmp/webino.os.locale.lock

    if [[ ! -f $lock ]]; then
        echo 'Setting locale...'

        sudo locale-gen en_US.UTF-8
        sudo locale-gen sk_SK.UTF-8
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
        sudo update-locale

        touch $lock
    else
        echo 'Locale already set...'
    fi
}

main
