#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It configures system mailer

main() {
    # return early on empty settings
    [[ -z $smtp_host || -z $smtp_user ]] && return

    # check
    if [[ "$(whereis nullmailer)" == *"/nullmailer"* ]]; then
        echo 'Mailer already installed...'
        return
    fi

    # install
    echo 'Installing mailer...'

    # read SMTP mailer password
    echo 'SMTP mailer password:'
    read -s smtp_password </dev/tty

    # remove pre-installed mailer
    sudo apt-get purge -y postfix* sendmail* exim*
    sudo apt-get autoremove -y

    # install mailer
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nullmailer

    # configure mailname
    echo $admin_mail | grep -oP '[^@]+$' | sudo tee /etc/mailname > /dev/null

    # configure mailer
    echo "$smtp_host smtp --port=587 --starttls --user=$smtp_user --pass=$smtp_password" | \
        sudo tee /etc/nullmailer/remotes > /dev/null

    echo $mail_host | sudo tee /etc/nullmailer/defaultdomain > /dev/null
    # TODO uc-first me host name
    echo $host_name | sudo tee /etc/nullmailer/me > /dev/null

    sudo chown mail:mail /etc/nullmailer/*

    service nullmailer reload
}

main
