#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It secures OS

main() {
    # check
    if [[ "$(whereis logwatch)" == *"/logwatch"* ]]; then
        echo 'OS already secured...'
        return
    fi

    # install
    echo 'Securing OS...'
    local data='@@host@@/data/'

    # logwatch
    echo 'Installing logwatch...'
    sudo apt-get install -y logwatch


    # TODO uc-first host name

    local file=/usr/share/logwatch/dist.conf/logwatch.conf
    echo "$(wget $data$file -qO- | \
            sed s/'%HOST_NAME%'/$host_name/g | \
            sed s/'%ADMIN_MAIL%'/$admin_mail/g)" | \
        sudo tee $file > /dev/null

    # fail2ban
    echo 'Installing fail2ban...'
    sudo apt-get install -y fail2ban

    local file=/etc/fail2ban/jail.local
    echo "$(wget $data$file -qO- | \
            sed s/'%ADMIN_MAIL%'/$admin_mail/g)" | \
        sudo tee $file > /dev/null

    sudo service fail2ban stop > /dev/null 2>&1 && \
    sudo service fail2ban start > /dev/null 2>&1 &
}

main
