#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It configures SSH

main() {
    # return early when SSH setup is disabled
    [[ -z "$with_ssh" ]] && return

    # lock check
    local lock=/tmp/webino.os.ssh.lock
    if [[ -f $lock ]]; then
        echo 'SSH already configured...'
        return
    fi

    # setup
    echo 'Configuring SSH...'
    local config=/etc/ssh/sshd_config

    # TODO generate random sysadmin username

    # TODO add sysadmin ssh key
    # add root SSH key
    if [[ -z "$no_interaction" ]]; then
        echo 'Root SSH authorized key:'
        read root_ssh_authorized_key </dev/tty

        [[ -n "$root_ssh_authorized_key" ]] && \
            sudo mkdir -p ~/.ssh && echo $root_ssh_authorized_key | sudo tee ~/.ssh/authorized_keys > /dev/null
    fi

    # allow only root login
    # TODO disable root login, allow sysadmin instead
    local is_ssh_root_only=$(grep 'AllowGroups root' $config)
    if [[ -z "$is_ssh_root_only" ]]; then
        echo 'Enabling SSH for root only ...'
        echo "AllowGroups root" | cat - $config | sudo tee $config > /dev/null
    fi

    # disable password
    # TODO disable root login
    sudo sed -i 's/LogLevel INFO/LogLevel VERBOSE/' $config
    sudo sed -i 's/PermitRootLogin yes/PermitRootLogin without-password/' $config
    sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' $config
    sudo sed -i 's/Subsystem sftp /usr/lib/openssh/sftp-server/Subsystem sftp internal-sftp/' $config
    sudo sed -i 's/UsePAM yes/UsePAM no/' $config

    # change default port
    local is_ssh_port_default=$(grep 'Port 22$' $config)
    if [[ -z "$is_ssh_port_default" ]]; then
        local ssh_port='22'$(echo $(< /dev/urandom tr -dc 0-9 | head -c2))
        sudo sed -i 's/Port .*/Port '$ssh_port'/' $config
        echo 'New SSH port: '$ssh_port
    fi

    sudo service ssh restart
    touch $lock
}

main
