#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It setups the operating system upgrades

main() {
    # exit early on clean
    [[ -n $clean ]] && return

    local data='@@host@@/data'
    local lock=/tmp/webino.os.upgrade.lock

    if [[ ! -f $lock ]]; then
        echo 'Setting up operating system upgrades...'

        # apticron & cron-apt
        echo 'Installing apticron & cron-apt...'
        sudo apt-get install -y apticron cron-apt

        sudo sed -i 's/EMAIL="root"/EMAIL="'$admin_mail'"/' /etc/apticron/apticron.conf
        sudo sed -i 's/# CUSTOM_FROM=""/CUSTOM_FROM="'$admin_mail'"/' /etc/apticron/apticron.conf
        sudo sed -i 's/# SYSTEM="foobar.example.com"/SYSTEM="'$host_name'"/' /etc/apticron/apticron.conf

        # disable listchanges
        if [ -f /etc/apt/listchanges.conf ]; then
            sudo sed -i 's/frontend=pager/frontend=text/' /etc/apt/listchanges.conf
        fi

        # set upgrade cron
        if [[ ! -f /etc/cron.d/upgrade ]]; then
            echo 'Installing upgrade CRON script...'
            sudo wget -qO /etc/cron.d/upgrade $data/etc/cron.d/upgrade
        fi

        touch $lock
    else
        echo 'Operating system upgrades already set...'
    fi
}

main
