#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04

main() {
    #----------+
    # defaults |
    #----------+
    _host_name=
    _host_ip=127.0.0.1
    _ssh=
    _smtp_host=
    _smtp_user=

    #----------+
    # get args |
    #----------+
    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        -host-name)
            _host_name=${argv[$n]}
            shift
            shift
        ;;
        -host-ip)
            _host_ip=${argv[$n]}
            shift
            shift
        ;;
        -ssh)
            _ssh=1
            shift
        ;;
        -smtp-host)
            _smtp_host=${argv[$n]}
            shift
            shift
        ;;
        -smtp-user)
            _smtp_user=${argv[$n]}
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
