#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs essential operating system tools

main() {
    #-------+
    # setup |
    #-------+
    local data='@@host@@/system/~data'
    echo -e "\nEssential setup..."

    # apt force ipv4
    local file=/etc/apt/apt.conf.d/99force-ipv4
    if [ -f $file ]; then
        echo 'Forcing IPv4...'
        root_file_write 'Acquire::ForceIPv4 "true";' $file
    else
        echo 'IPv4 already forced...'
    fi

    #--------------------+
    # essential packages |
    #--------------------+
    sudo apt-get clean
    sudo apt-get update

    install \
        update-manager-core \
        build-essential \
        debconf-utils \
        pkg-config \
        autoconf \
        automake \
        libtool \
        re2c \
        htop \
        curl \
        unzip \
        git
        
    #-------------------------------+
    # java runtime (local|dev only) |
    #-------------------------------+
    [[ ( $_env_local || $_env_dev ) && ! $(java -version 2> /dev/null) ]] && \
        install default-jre

    #----------------------+
    # hosts-fix (dev only) |
    #----------------------+
    if [[ $_env_dev ]]; then
        if [[ $(systemctl --version 2> /dev/null) ]]; then
            #-----------------+
            # systemd support |
            #-----------------+
            local file=/etc/systemd/system/hosts-fix.service
            if [[ ! -f $file ]]; then
                echo 'Installing hosts-fix systemd script...'
                root_file_wget $data$file $file
                sudo systemctl enable hosts-fix.service
            fi
        else
            #--------------------------+
            # upstart support (legacy) |
            #--------------------------+
            local file=/etc/init/hosts-fix.conf
            if [[ ! -f $file ]]; then
                echo 'Installing hosts-fix upstart script...'
                root_file_wget $data$file $file
                sudo initctl reload-configuration > /dev/null 2>&1 &
            fi
        fi
    fi

    #-------------------+
    # rsyslog logrotate |
    #-------------------+
    local file=/etc/logrotate.d/rsyslog
    sudo sed -i 's/rotate 4/rotate 7/g' $file
    sudo sed -i 's/weekly/daily/g' $file
}

main
