#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs essential operating system tools

main() {
    #------------+
    # lock check |
    #------------+
    local lock=/tmp/webino.system.essential.lock
    if [[ -f $lock ]]; then
        echo 'Essential tools already installed...'
        return
    fi

    #---------+
    # install |
    #---------+
    local data='@@host@@/system/~data'
    echo 'Installing essential tools...'

    # apt force ipv4
    echo 'Acquire::ForceIPv4 "true";' | sudo tee /etc/apt/apt.conf.d/99force-ipv4

    sudo apt-get clean
    sudo apt-get update

    sudo apt-get install -y \
        update-manager-core \
        build-essential \
        debconf-utils \
        pkg-config \
        autoconf \
        automake \
        libtool \
        re2c \
        curl \
        git

    # TODO remove useless dependencies
    #sudo apt-get install -y \
    #    libwww-perl \
    #    libkrb5-dev \

    #-------------------------------+
    # java runtime (local|dev only) |
    #-------------------------------+
    [[ ( $_env_local || $_env_dev ) && ! $(java -version 2> /dev/null) ]] && \
        sudo apt-get install -y default-jre

    #----------------------+
    # hosts-fix (dev only) |
    #----------------------+
    if [[ $_env_dev ]]; then
        if [[ $(systemctl --version 2> /dev/null) ]]; then
            #-----------------+
            # systemd support |
            #-----------------+
            local file=/etc/systemd/system/hosts-fix.service
            if [[ ! -f $file ]]; then
                echo 'Installing hosts-fix systemd script...'
                sudo wget $data$file -qO $file
                sudo systemctl enable hosts-fix.service
            fi
        else
            #--------------------------+
            # upstart support (legacy) |
            #--------------------------+
            local file=/etc/init/hosts-fix.conf
            if [[ ! -f $file ]]; then
                echo 'Installing hosts-fix upstart script...'
                sudo wget $data$file -qO $file
                sudo initctl reload-configuration > /dev/null 2>&1 &
            fi
        fi
    fi

    #------+
    # lock |
    #------+
    touch $lock
}

main
