#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs fail2ban

main() {
    #-------------------------+
    # check already installed |
    #-------------------------+
    if [[ "$(whereis fail2ban)" == *"/fail2ban"* ]]; then
        echo 'Fail2ban already installed...'
        return
    fi

    #---------+
    # install |
    #---------+
    local data='@@host@@/system/~data'
    echo 'Installing fail2ban...'

    sudo apt-get install -y fail2ban

    #-----------+
    # configure |
    #-----------+
    local file=/etc/fail2ban/jail.local
    echo "$(wget $data$file -qO- | \
            sed s/'%HOST_IP%'/$_host_ip/g | \
            sed s/'%ADMIN_MAIL%'/$_admin_mail/g)" | \
        sudo tee $file > /dev/null

    # ssh jail
    local file=/etc/fail2ban/jail.d/ssh.conf
    sudo wget $data$file -qO $file

    #-----------------+
    # service restart |
    #-----------------+
    sudo service fail2ban stop > /dev/null 2>&1 && \
    sudo service fail2ban start > /dev/null 2>&1 &
}

main
