#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It configures operating system

main() {
    echo 'System setup...'

    #------------------+
    # environment info |
    #------------------+
    echo -n 'Environment: '
    [[ $_env_local ]] && echo 'local'
    [[ $_env_dev ]]   && echo 'development'
    [[ $_env_pub ]]   && echo 'public'
    echo

    #---------+
    # general |
    #---------+
    load system/arguments "$@"
    load system/info
    load system/locale
    load system/essential

    #----------------------+
    # extra (dev|pub only) |
    #----------------------+
    if [[ $_env_dev || $_env_pub ]]; then
        load system/mailer
        load system/upgrades
        load system/logwatch
        load system/fail2ban
        load system/ssh
    fi

    #------+
    # done |
    #------+
    echo -e "\nSystem setup done..."
}

main "$@"
