#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It resolves host operating system info

main() {
    #------------------------------------+
    # resolve server info (dev|pub only) |
    #------------------------------------+
    if [[ ! $_host_name && ( ! $_env_dev || ! $_env_pub ) ]]; then
        echo 'Resolving host info...'
        _host_ip=$(wget ipecho.net/plain -qO-)
        _host_name=$(hostname)
    fi

    #----------------------+
    # server info defaults |
    #----------------------+
    if [[ ! $_host_name ]]; then
        echo 'Using default host info...'
        _host_name=webino.local
    fi

    #------------------------+
    # sysadmin email default |
    #------------------------+
    _admin_email=${_admin_email-'sysadmin@'$_host_name}

    #----------------+
    # show host info |
    #----------------+
    echo 'Host IP: '$_host_ip
    echo 'Host name: '$_host_name
    echo 'Admin email: '$_admin_email
    echo
}

main
