#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It fixes operating system locales

main() {
    #------------+
    # lock check |
    #------------+
    local lock=/tmp/webino.system.locale.lock
    if [[ -f $lock ]]; then
        echo 'System locales already configured...'
        return
    fi

    #-----------+
    # configure |
    #-----------+
    echo 'Configuring system locales...'
    # TODO optional locales support
    sudo locale-gen en_US.UTF-8
    sudo locale-gen sk_SK.UTF-8
    sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
    sudo update-locale

    #------+
    # lock |
    #------+
    touch $lock
}

main
