#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It fixes operating system locales

setup_locale()
{
    echo 'Configuring system locales...'

    local configured=$(locale -a)
    local to_configure=''

    for l in $@; do
        if [ "$(echo $configured | grep -o $l 2>/dev/null)" ]; then
            echo $l' \ configured'
        else
            echo $l' \ configuring'
            to_configure=$to_configure' '$l
        fi
    done
    
    if [ "$to_configure" ]; then
        sudo locale-gen $to_configure
        sudo DEBIAN_FRONTEND=noninteractive dpkg-reconfigure locales
        sudo update-locale
        return 0
    fi
    
    echo 'Locales already configured...'
    return 1
}

main() {
    #-------+
    # setup |
    #-------+
    # TODO optional locales support
    #setup_locale en_US.utf8 sk_SK.utf8
    return 0
}

main
