#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs logwatch

main() {
    #---------+
    # install |
    #---------+
    local data='@@host@@/system/~data'
    echo 'Logwatch...'
    install logwatch

    #-----------+
    # configure |
    #-----------+
    local file=/usr/share/logwatch/dist.conf/logwatch.conf
    [ -f "$file" ] || \
            echo "$(wget $data$file -qO- | \
                sed s/'%HOST_NAME%'/$_host_name/g | \
                sed s/'%ADMIN_EMAIL%'/$_admin_email/g)" | \
            sudo tee $file > /dev/null
}

main
