#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It configures system mailer

main() {
    #--------------------------------+
    # return early on empty settings |
    #--------------------------------+
    [[ ! $_smtp_host || ! $_smtp_user ]] && return
    
    #-------+
    # setup |
    #-------+
    echo -e "\nMailer setup..."

    #---------------------------+
    # read SMTP mailer password |
    #---------------------------+
    local smtp_password=
    if [[ ! $_no_interaction ]]; then
        echo 'SMTP mailer password:'
        read -s smtp_password </dev/tty
    fi

    #-----------------------------+
    # remove pre-installed mailer |
    #-----------------------------+
    uninstall postfix* sendmail* exim*

    #---------+
    # install |
    #---------+
    install nullmailer

    #--------------------+
    # configure mailname |
    #--------------------+
    local mail_host=$(echo $_admin_email | grep -oP '[^@]+$')
    root_file_write $mail_host /etc/mailname

    #------------------+
    # configure mailer |
    #------------------+
    local file=/etc/nullmailer/remotes
    if [ ! "$(grep -oP "^$(echo $_smtp_host | sed -e 's/\./\\\./g')" $file) " 2>/dev/null ] \
         || [ ! "$(grep -oP "user=$(echo $_smtp_user | sed -e 's/\./\\\./g') " $file)" 2>/dev/null ]
    then
        root_file_write "$_smtp_host smtp --port=587 --starttls --user=$_smtp_user --pass=$smtp_password" $file
    fi

    root_file_write $mail_host /etc/nullmailer/defaultdomain
    root_file_write $_host_name /etc/nullmailer/me

    sudo chown mail:mail /etc/nullmailer/*

    #----------------+
    # service reload |
    #----------------+
    sudo service nullmailer reload &
}

main
