#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It configures operating system

load() {
    #-------------------------+
    # load remote bash source |
    #-------------------------+
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino && rm /tmp/webino
}

main() {
    echo -e "\nMachine setup for Webino™...\n"

    #------+
    # init |
    #------+
    load lib/trap
    load lib/spinner
    load arguments "$@"

    #-------+
    # setup |
    #-------+
    load system/general
}

main "$@"
