#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It configures SSH

main() {
    #------------------------------------+
    # return early on disabled SSH setup |
    #------------------------------------+
    [[ ! $_ssh ]] && return

    #-------+
    # setup |
    #-------+
    local config=/etc/ssh/sshd_config
    echo -e "\nSSH setup..."

    #---------------------+
    # add sysadmin sudoer |
    #---------------------+
    if ! group_exists sysadmin; then
        echo -e "\nAdding sysadmin user..."
        local sysadmin="s$(rand_word 8)"
        local sysadmin_pwd=$(rand_word 8)
        sudo groupadd sysadmin
        sudo useradd -ms /bin/bash -Ng sysadmin -G sudo -c sysadmin $sysadmin
        echo -e "$sysadmin_pwd\n$sysadmin_pwd" | sudo passwd $sysadmin
        local ssh_filepath=$(user_ssh_keygen $sysadmin id_rsa)
        local msg="Sysadmin\nUsername: $sysadmin\nPassword: $sysadmin_pwd\nSSH key: \n$(printf -- "$(cat $ssh_filepath)")"
        setup_log "$msg"

        # add sysadmin SSH key
        local file='/home/'$sysadmin'/.ssh/authorized_keys'
        if ! sudo test -f $file; then
            if [[ ! $_no_interaction ]]; then
                echo 'Sysadmin SSH authorized key:'
                read sysadmin_authorized_key </dev/tty

                [[ -n "$sysadmin_authorized_key" ]] && \
                    sudo su $sysadmin -c "mkdir -p ~/.ssh; printf $sysadmin_authorized_key | tee -a $file > /dev/null"
            fi
        fi
    fi

    #---------------------------+
    # allow sysadmin login only |
    #---------------------------+
    local is_ssh_root_only=$(grep 'AllowGroups sysadmin' $config)
    if [[ ! $is_ssh_root_only ]]; then
        echo 'Enabling SSH for sysadmin group only ...'
        echo "AllowGroups sysadmin" | cat - $config | sudo tee $config > /dev/null
    fi

    #------------------------+
    # disable password login |
    #------------------------+
    sudo sed -i 's/LogLevel INFO/LogLevel VERBOSE/' $config
    sudo sed -i 's/#\?PermitRootLogin yes/PermitRootLogin no/' $config
    sudo sed -i 's/#\?PermitRootLogin without-password/PermitRootLogin no/' $config
    sudo sed -i 's/#\?PasswordAuthentication yes/PasswordAuthentication no/' $config
    sudo sed -i 's/UsePAM yes/UsePAM no/' $config

    #---------------------+
    # change default port |
    #---------------------+
    local is_ssh_port_default=$(grep 'Port 22$' $config)
    if [[ $is_ssh_port_default ]]; then
        local ssh_port='22'$(echo $(< /dev/urandom tr -dc 0-9 | head -c2))
        sudo sed -i 's/Port .*/Port '$ssh_port'/' $config
        local msg='New SSH port: '$ssh_port
        setup_log $msg
    fi

    #-----------------+
    # service restart |
    #-----------------+
    sudo service ssh restart &
}

main
