#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It configures SSH

main() {
    #------------------------------------+
    # return early on disabled SSH setup |
    #------------------------------------+
    [[ ! $_with_ssh ]] && return

    #-------+
    # setup |
    #-------+
    local config=/etc/ssh/sshd_config
    echo 'SSH setup...'

    # TODO add sysadmin sudoer
    # TODO generate random sysadmin username

    #------------------+
    # add root SSH key |
    #------------------+
    # TODO add sysadmin ssh key
    local file=/root/.ssh/authorized_keys
    if ! sudo test -f $file; then
        if [[ ! $_no_interaction ]]; then
            echo 'Root SSH authorized key:'
            read root_ssh_authorized_key </dev/tty

            [[ -n "$root_ssh_authorized_key" ]] && \
                sudo mkdir -p ~/.ssh && echo $root_ssh_authorized_key | sudo tee $file > /dev/null
        fi
    fi

    #-----------------------+
    # allow root login only |
    #-----------------------+
    # TODO disable root login, allow sysadmin only instead
    local is_ssh_root_only=$(grep 'AllowGroups root' $config)
    if [[ ! $is_ssh_root_only ]]; then
        echo 'Enabling SSH for root only ...'
        echo "AllowGroups root" | cat - $config | sudo tee $config > /dev/null
    fi

    #------------------------+
    # disable password login |
    #------------------------+
    # TODO disable root login
    sudo sed -i 's/LogLevel INFO/LogLevel VERBOSE/' $config
    sudo sed -i 's/PermitRootLogin yes/PermitRootLogin without-password/' $config
    sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' $config

    #-----------+
    # configure |
    #-----------+
    sudo sed -i 's~Subsystem sftp /usr/lib/openssh/sftp-server~Subsystem sftp internal-sftp~' $config
    sudo sed -i 's/UsePAM yes/UsePAM no/' $config

    #---------------------+
    # change default port |
    #---------------------+
    local is_ssh_port_default=$(grep 'Port 22$' $config)
    if [[ $is_ssh_port_default ]]; then
        local ssh_port='22'$(echo $(< /dev/urandom tr -dc 0-9 | head -c2))
        sudo sed -i 's/Port .*/Port '$ssh_port'/' $config
        local msg='New SSH port: '$ssh_port
        setup_log $msg
    fi

    #-----------------+
    # service restart |
    #-----------------+
    sudo service ssh restart &
}

main
