#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/system -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It configures operating system upgrades

main() {
    #-------+
    # setup |
    #-------+
    local data='@@host@@/system/~data'
    echo -e "\nOperating system upgrades setup..."

    #------------------+
    # apticron install |
    #------------------+
    echo 'Apticron...'
    install apticron

    sudo sed -i 's/EMAIL="root"/EMAIL="'$_admin_email'"/' /etc/apticron/apticron.conf
    sudo sed -i 's/# SYSTEM="foobar.example.com"/SYSTEM="'$_host_name'"/' /etc/apticron/apticron.conf

    #------------------------+
    # apt-listchanges config |
    #------------------------+
    local file=/etc/apt/listchanges.conf
    if [[ -f $file ]]; then
        sudo sed -i 's/frontend=pager/frontend=text/' $file
        sudo sed -i 's/email_address=root/email_address='$_admin_email'/' $file
    fi

    #------------------+
    # set upgrade cron |
    #------------------+
    local file=/etc/cron.d/upgrade
    if [[ ! -f $file ]]; then
        echo 'Installing upgrade CRON script...'
        root_file_wget $data$file $file
    fi

    #-----------+
    # logrotate |
    #-----------+
    local file=/etc/logrotate.d/upgrade
    if [[ ! -f $file ]]; then
        echo 'Configuring upgrade logrotate...'
        root_file_wget $data$file $file
    fi
}

main
