#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It installs MySQL database

main() {
    cd /tmp
    local data='@@host@@/data/'
    local lock=webino.sw.mysql.client.lock

    if [[ ! -f $lock ]]; then
        echo "Installing MySQL client..."

        # resolve client credentials
        if [ -z "${mysql_client_user-}" ]; then
            echo "Generating MySQL client user..."
            mysql_client_user=$(echo $(< /dev/urandom tr -dc a-z0-9 | head -c6))
        fi
        if [ -z "${mysql_client_password-}" ]; then
            echo "Generating MySQL password for user \`$mysql_client_user\`..."
            mysql_client_password=$(echo $(< /dev/urandom tr -dc a-z0-9 | head -c12))
        fi

        # resolve client home
        local client_home=$(echo ~)
        if [ "$(id www-data 2> /dev/null)" ]; then
            client_home=$(echo ~www-data)
        fi

        if [[ -d "$client_home" ]]; then
            echo "MySQL client home \`$client_home\`..."

            # create client config
            local file=$client_home'/.my.cnf'
            if [[ ! -f $file ]]; then
                echo "Creating MySQL client config..."

                echo "$(wget -qO- @@host@@/data/home/example/.my.cnf | \
                    sed s/'%USER%'/$mysql_client_user/ | \
                    sed s/'%PASSWORD%'/$mysql_client_password/)" | \
                    sudo tee $file > /dev/null

                sudo chown www-data:root $ile
                sudo chmod 660 $file
            fi

            # create mysql client user
            echo "Creating MySQL client user..."
            sudo -i mysql -e "CREATE USER '$mysql_client_user'@'localhost' IDENTIFIED BY '$mysql_client_password';"
            sudo -i mysql -e "$(wget ${data}extra/mysql-grant-client.sql -qO- | sed s/'%USER%'/$mysql_client_user/g)"
        fi

        touch $lock
    else
        echo 'MySQL client already installed...'
    fi
}

main
