#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs MySQL database

main() {
    cd /tmp
    local data='@@host@@/data'
    local lock=seed.sw.mysql.server.lock

    if [[ ! -f $lock ]]; then
        echo "Installing MySQL server..."

        # resolve mysql root credentials
        if [ -z "${mysql_root_password-}" ]; then
            echo "Generating MySQL password for user \`root\`..."
            mysql_root_password=$(echo $(< /dev/urandom tr -dc a-z0-9 | head -c12))
        fi

        # non-interactive
        sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password '$mysql_root_password
        sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password '$mysql_root_password
        sudo apt-get install -y mysql-server

        # create root config
        if [[ ! -f /root/.my.cnf ]]; then
            echo "Creating MySQL root config..."

            echo "$(wget -qO- @@host@@/data/home/example/.my.cnf | \
                sed s/'%USER%'/root/ | sed s/'%PASSWORD%'/$mysql_root_password/)" | \
                sudo tee /root/.my.cnf > /dev/null

            sudo chmod 600 /root/.my.cnf
        fi

        touch $lock
    else
        echo 'MySQL server already installed...'
    fi
}

main
