#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/git-srv -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs Git server

main() {
    cd /tmp/php || return

    echo 'Git fetch server setup...'
    local data='@@host@@/git-srv/~data/'

    echo 'Adding git-srv user...'
    sudo useradd -r git-srv
    sudo mkdir -p /srv/git

    if [[ $(systemctl --version 2> /dev/null) ]]; then
        # Systemd
        echo 'Installing Git fetch server...'
        local file=/etc/systemd/system/git-srv.service
        if [[ ! -f $file ]]; then
            sudo wget $data$file -qO $file
            sudo systemctl enable git-srv.service
        fi
    else
        # Upstart
        echo 'Installing Git fetch server...'
        local file=/etc/init/git-srv.conf
        if [[ ! -f $file ]]; then
            sudo wget $data$file -qO $file
            sudo initctl reload-configuration > /dev/null 2>&1 &
        fi
    fi

    echo 'Git fetch server setup done...'
}

main
