before_install:
  - "echo 'Fixing wget SNI for Ubuntu 12.04' && wget http://ppa.launchpad.net/nathan-renniewaldock/ppa/ubuntu/pool/main/w/wget/wget_1.14-1~ppa1~precise_amd64.deb && sudo dpkg -i wget_1.14-1~ppa1~precise_amd64.deb
  && sudo apt-get install -f"
script:
  - wget https://get.webino.org/devkit -O - | sh
