language: bash
matrix:
  include:
    - env: TEST=apache
    - env: TEST=apache-pub
    - env: TEST=mysql
    - env: TEST=php
    - env: TEST=php7
    - env: TEST=devkit
    - env: TEST=dev-module
  allow_failures:
    - env: TEST=apache-pub
before_install:
  - sudo chmod o+w /home/travis -R
script:
  - tests/bootstrap
env:
  global:
    - GH_REF=github.com/webino/get.webino.org
    - secure: O2T13SnWVLTvmIWRxmWPh8VB7j1VOk2qjxXUfvLTZOVFInoJz0cy/Vo5K82Hug+qdz4ncH3bDjUOKiyFinkZr3uoxBOVlam9Z61XiHeHBluWbcKhSW2IW2chc5F8RVHDxCYa79q9vLoIwDNWDVe42E9BY+jCx32zSXhWlgTetaM=
