#!/bin/sh

# This is the Webino Devkit install script!
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    curl https://get.webino.org/devkit | sh
#
# Webino Devkit currently supports:
#   - Linux: Ubuntu 14.04
#
# Version: @@version@@
#
# Requires
#   - Node.js
#   - PHP5
#   - Git, Gitflow
#   - Graphviz
#
# What this script does?
#   - It installs webino-devkit via npm globally
#   - It setups user Webino workspace

APT_INSTALL=""

# Check npm
if [ "$(sudo npm -v 2> /dev/null)" = "" ]
then
    echo "Installing Node.js"
    curl -sL https://deb.nodesource.com/setup | sudo bash
    APT_INSTALL="$APT_INSTALL nodejs"
fi

# Check PHP
if [ "$(sudo php -v 2> /dev/null)" = "" ]
then
    echo "Installing PHP5"
    APT_INSTALL="$APT_INSTALL php5"
fi

# Check Git
if [ "$(sudo git --version 2> /dev/null)" = "" ]
then
    echo "Installing Git"
    APT_INSTALL="$APT_INSTALL git"
fi

# Check Gitflow
if [ "$(sudo git flow 2> /dev/null)" = "" ]
then
    echo "Installing Gitflow"
    APT_INSTALL="$APT_INSTALL git-flow"
fi

# Check Graphviz
if [ "$(sudo dpkg -s graphviz 2> /dev/null)" = "" ]
then
    echo "Installing Graphviz"
    APT_INSTALL="$APT_INSTALL graphviz"
fi

# Install apt-get packages
if [ "$APT_INSTALL" != "" ]
then
    sudo apt-get update 
    sudo apt-get install -y "$APT_INSTALL"
fi

# Check grunt
# TODO this should be required by devkit package.json
if [ "$(sudo grunt --version 2> /dev/null)" = "" ]
then
    echo "\nInstalling Grunt.js\n"
    sudo npm install grunt-cli -g
fi

# Installing devkit
echo "\nInstalling Webino Development Kit\n"
sudo npm install webino-devkit -g --unsafe-perm

# Check instalation
if [ "$(webino 2> /dev/null)" = "" ]
then
    exit 1
fi

# Initializing user workspace
webino workspace

# Success
cat <<"EOF"

To get started:

  $ webino

Or see the docs at:

  http://open.webino.org/docs

EOF
