#!/bin/sh

# This is the Webino Devkit install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    wget https://get.webino.org/devkit -qO - | sh
#
# Webino Devkit currently supports:
#   - Linux: Ubuntu 14.04
#
# Requires
#   - Node.js
#   - PHP5
#   - Git, Gitflow
#   - Graphviz
#
# What this script does?
#   - It installs webino-devkit via npm globally
#   - It setups user Webino workspace

APT_INSTALL=""

# Check Git
[ "$(git --version 2> /dev/null)" = "" ] && APT_INSTALL="$APT_INSTALL git"
# Check Gitflow
[ "$(git flow 2> /dev/null)" = "" ] && APT_INSTALL="$APT_INSTALL git-flow"
# Check Graphviz
[ "$(dpkg -s graphviz 2> /dev/null)" = "" ] && APT_INSTALL="$APT_INSTALL graphviz"

# Install apt-get packages
if [ "$APT_INSTALL" != "" ]
then
    echo "Installing: $APT_INSTALL"
    sudo apt-get update 
    sudo apt-get install -y $APT_INSTALL
fi

# Check PHP
if [ "$(php -v 2> /dev/null)" = "" ]
then
    # Building PHP from source
    wget https://get.webino.org/seed/php -qO - | sh
fi

# Check npm
if [ "$(npm -v 2> /dev/null)" = "" ]
then
    echo 'Installing: Node.js'
    wget https://deb.nodesource.com/setup -qO - | sudo bash
    sudo apt-get install nodejs
fi

# Check grunt
# TODO this should be required by devkit package.json
if [ "$(grunt --version 2> /dev/null)" = "" ]
then
    echo 'Installing Grunt.js'
    sudo npm install grunt-cli -g
fi

# Installing devkit
echo "\nInstalling Webino Development Kit\n"
sudo npm install webino-devkit -g --unsafe-perm

# Check instalation
if [ "$(webino 2> /dev/null)" = '' ]
then
    exit 1
fi

# Initializing user workspace
webino workspace

# Success
cat <<"EOF"

To get started:

  $ webino

Or see the docs at:

  http://open.webino.org/docs

EOF
