#!/bin/sh

# This is the Webino Devkit install script!
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    curl https://get.webino.org/devkit | sh
#
# Webino Devkit currently supports:
#   - Linux: Ubuntu 14.04
#
# Requires
#   - Node.js
#   - PHP5
#   - Git, Gitflow
#   - Graphviz
#
# What this script does?
#   - It installs webino-devkit via npm globally
#   - It setups user Webino workspace

APT_INSTALL=""

# Check npm
if [ "$(npm -v 2> /dev/null)" = "" ]
then
    echo "\nInstalling Node.js\n"
    curl -sL https://deb.nodesource.com/setup | sudo bash
    APT_INSTALL="$APT_INSTALL nodejs"
fi

# Check PHP
if [ "$(php -v 2> /dev/null)" = "" ]
then
    echo "\nInstalling Node.js\n"
    APT_INSTALL="$APT_INSTALL php5"
fi

# Check Git
if [ "$(git --version 2> /dev/null)" = "" ]
then
    echo "\nInstalling Git\n"
    APT_INSTALL="$APT_INSTALL git"
fi

# Check Gitflow
if [ "$(git flow 2> /dev/null)" = "" ]
then
    echo "\nInstalling Git\n"
    APT_INSTALL="$APT_INSTALL git-flow"
fi

# Check Graphviz
if [ "$(dpkg -s graphviz 2> /dev/null)" = "" ]
then
    APT_INSTALL="$APT_INSTALL graphviz"
fi

# Install apt-get packages
[ "$APT_INSTALL" = "" ] && apt-get update && apt-get install -y "$APT_INSTALL"

# Check grunt
# TODO this should be required by devkit package.json
if [ "$(grunt --version 2> /dev/null)" = "" ]
then
    echo "\nInstalling Grunt.js\n"
    sudo npm install grunt-cli -g
fi

# Installing devkit
echo "\nInstalling Webino Development Kit\n"
sudo npm install webino-devkit -g --unsafe-perm

# Check instalation

# Initializing user workspace
webino workspace

# Success
cat <<"EOF"

To get started:

  $ webino

Or see the docs at:

  http://open.webino.org/docs

EOF
