#!/bin/sh

# This is the Webino install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino?
# Just open up your terminal and type:
#
#    wget https://get.webino.org -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - Workstation setup [TODO]
#   - Webino Devkit installation

main() {
    # TODO wget https://get.webino.org/seed -qO- | sh
    wget https://get.webino.org/devkit -qO- | sh
}

main
