#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/certbot -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs Let’s Encrypt certificate bot

main() {
    cd /usr/local/bin || return
    local data='@@host@@/certbot/~data/'
    echo -e "\nWebino Certbot setup...\n"

    if [[ $(certbot --version 2>/dev/null) ]];then
        echo -e "\nWebino Certbot already installed...\n"
        return
    fi

    sudo snap install core
    sudo snap refresh core
    sudo snap install --classic certbot
    sudo ln -s /snap/bin/certbot /usr/bin/certbot
    sudo certbot --version

    # renew cron
    local post_hook=
    [[ $(apachectl -v 2>/dev/null) ]] && post_hook+=$($([[ "$post_hook" ]] && echo "$post_hook & ")'apachectl graceful'; echo "$post_hook")
    [[ $(postfix status 2>/dev/null) ]] && post_hook+=$($([[ "$post_hook" ]] && echo "$post_hook & ")'service postfix reload'; echo "$post_hook")
    [[ $(dovecot --version 2>/dev/null) ]] && post_hook+=$($([[ "$post_hook" ]] && echo "$post_hook & ")'service dovecot reload'; echo "$post_hook")

    local file=/etc/cron.daily/certbot-renew
    wget -qO- $data$file | \
        sed s/'%POST_HOOK%'/"$post_hook"/g | \
        sudo tee "$file" > /dev/null

    # renew log rotate
    local file=/etc/logrotate.d/certbot-renew
    if [[ ! -f $file ]]; then
        echo 'Configuring certbot-renew logrotate...'
        root_file_wget $data$file -qO $file
    fi

    echo -e "\nWebino Certbot setup done...\n"
}

main
