#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/certbot -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs Let’s Encrypt certificate bot

main() {
    cd /usr/local/bin || return
    local data='@@host@@/certbot/~data/'
    echo -e "\nWebino Certbot setup...\n"

    if [[ $(whereis certbot-auto 2>/dev/null) ]];then
        echo -e "\nWebino Certbot already installed...\n"
        return
    fi

    sudo wget https://dl.eff.org/certbot-auto
    sudo chmod a+x ./certbot-auto
    sudo certbot-auto certonly --webroot -w /undefined -d undefined.com -d www.undefined.com || true

    # TODO
    # renew cron

    # renew log rotate
    local file=/etc/logrotate.d/certbot-renew
    if [[ ! -f $file ]]; then
        echo 'Configuring certbot-renew logrotate...'
        sudo wget $data$file -qO $file
    fi

    echo -e "\nWebino Certbot setup done...\n"
}

main
