#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# Original source
# http://fitnr.com/showing-a-bash-spinner.html

spinner()
{
    local pid=$!
    local delay=.5
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf "[%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}
