#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04

#-----------------+
# Write setup log |
#-----------------+
setup_log()
{
    echo $@ && echo $@ >> /root/.webino.log
}

#----------------+
# Show setup log |
#----------------+
setup_done()
{
    local log=/root/.webino.log
    if [[ -s $log ]]; then
        hr
        cat $log
        hr
    fi
}

#------------------+
# Horizontal ruler |
#------------------+
hr()
{
    printf '%*s\n' $((${COLUMNS:-$(tput cols)}-1)) '' | tr ' ' -
}

#--------------------+
# Packages installer |
#--------------------+
install() 
{
    local to_install=''
    local installed=$(dpkg -l)

    for n in $@; do
        if [ "$(echo $installed | grep -o $n 2>/dev/null)" ]; then
            echo $n' \ installed'
            continue
        fi
        echo $n' \ installing'
        to_install=$to_install' '$n
    done
    
    if [ "$to_install" ]; then
        echo 'Installing:'$to_install
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y "$to_install"
        return 0
    fi
    
    echo 'Nothing to install...'
    return 1
}

#-----------------+
# Root file write |
#-----------------+
root_file_put()
{
    echo $1 | sudo tee $2 > /dev/null
}

#-------------------+
# Root file web get |
#-------------------+
root_file_wget()
{
    sudo wget $1 -qO $2
}
