#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/certbot -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs Let’s Encrypt certificate bot

main() {
    # install
    cd /usr/local/bin
    local data='@@host@@/data/'
    sudo wget https://dl.eff.org/certbot-auto
    sudo chmod a+x ./certbot-auto
    sudo certbot-auto certonly --webroot -w /undefined -d undefined.com -d www.undefined.com || true

    # TODO
    # renew cron


    # renew log rotate
    local file=/etc/logrotate.d/certbot-renew
    if [[ ! -f $file ]]; then
        echo 'Configuring certbot-renew logrotate...'
        sudo wget -qO $file $data$file
    fi
}

main
