#!/bin/bash

# This is the Webino? Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/apache -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp/httpd
    if [ ! -f builded.lock ]; then
        echo 'Building Apache...'

        # optional arguments
        local opt=''
        [[ -z $env_local ]] && local opt='--disable-autoindex';

        sudo sh ./configure \
            --bindir=/usr/bin \
            --sbindir=/usr/sbin \
            --sysconfdir=/etc/apache2 \
            --with-perl \
            --with-ssl \
            --enable-ssl \
            --enable-rewrite \
            --enable-suexec \
            --enable-info \
            --enable-socache-shmbc \
            $opt

        make
        sudo make install
        touch builded.lock
    else
        echo 'Apache already builded...'
    fi
}

main
