#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/apache -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp/httpd

    if [ ! -f daemon.lock ]; then
        echo 'Installing upstart daemon...'
        if [ ! -f /etc/init/apache2.conf ]; then
            sudo wget -qO /etc/init/apache2.conf https://get.webino.org/seed/data/etc/init/apache2.conf
        fi

        sudo initctl reload-configuration
        touch daemon.lock
    else
        echo 'Upstart daemon already installed...'
    fi
}

main
