#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/apache -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp

    # Apache APR
    if [ ! -d apr ]; then
        echo 'Downloading Apache APR... '$apache_apr_version
        wget 'http://tux.rainside.sk/apache/apr/apr-'$apache_apr_version'.tar.gz' \
            -O apr.tar.gz && tar xvf apr.tar.gz & spinner $! && rm apr.tar.gz 2>&1

        mv 'apr-'$apache_apr_version apr
    else
        echo 'Apache APR already downloaded...'
    fi

    # Apache APR Util
    if [ ! -d apr-util ]; then
        echo 'Downloading Apache APR Util... '$apache_apr_util_version
        wget 'http://tux.rainside.sk/apache/apr/apr-util-'$apache_apr_util_version'.tar.gz' \
            -O apr-util.tar.gz && tar xvf apr-util.tar.gz & spinner $! && rm apr-util.tar.gz 2>&1

        mv 'apr-util-'$apache_apr_util_version apr-util
    else
        echo 'Apache APR Util already downloaded...'
    fi

    # Apache
    if [ ! -d httpd ]; then
        echo 'Downloading Apache... '$apache_version
        wget 'http://tux.rainside.sk/apache/httpd/httpd-'$apache_version'.tar.gz' \
            -O httpd.tar.gz && tar xvf httpd.tar.gz & spinner $! && rm httpd.tar.gz 2>&1

        mv httpd-* httpd
        mv apr httpd/srclib && mv apr-util httpd/srclib
    else
        echo 'Apache already downloaded...'
    fi
}

main
