#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/apache -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds Apache from source

main() {
    # return early when File2ban not installed
    [[ ! -f /etc/fail2ban/jail.local ]] && return 0

    local data='@@host@@/seed/data'
    local is_configured=$(grep apache /etc/fail2ban/jail.local)

    if [[ -z "$is_configured" ]]; then
        echo 'Installing Fail2ban for Apache...'

        echo "$(wget $data/etc/fail2ban/jail.local-apache -qO-)" | \
            sudo tee --append /etc/fail2ban/jail.local > /dev/null

        # TODO fix for PHP SSH
        #sudo service fail2ban restart
    else
        echo 'Fail2ban for Apache already installed...'
    fi
}

main
