#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/apache -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    # resolve latest versions
    apache_version_latest=$(echo $(wget -qO- http://www.apache.org/dist/httpd/Announcement2.4.txt \
        | grep -Eom 1 'Server 2\.4\.[0-9]+ Released' | grep -Eom 1 '[0-9\.]+'))

    apache_apr_version_latest=$(echo $(wget -qO- http://apr.apache.org/download.cgi \
        | grep -Eom 1 'APR 1\.5\.[0-9]+ is the best' | grep -Eom 1 '[0-9\.]+'))

    apache_apr_util_version_latest=$(echo $(wget -qO- http://apr.apache.org/download.cgi \
        | grep -Eom 1 'APR-util 1\.5\.[0-9]+ is the best' | grep -Eom 1 '[0-9\.]+'))

    apache_version=${apache_version-$apache_version_latest}
    apache_apr_version=${apache_apr_version-$apache_apr_version_latest}
    apache_apr_util_version=${apache_apr_util_version-$apache_apr_util_version_latest}

    # TODO server name (local only)
    #apache_server_name='webino.'$([[ $USER == 'webino' ]] && echo 'local' || echo $USER)

    # clean the Apache build
    [[ -n $clean ]] && load sw/apache/clean && return

    # remove pre-installed
    echo 'Removing pre-installed Apache...'
    sudo apt-get purge -y apache*
    sudo apt-get autoremove -y

    echo 'Seeding Apache '$apache_version
    load sw/apache/download
    load sw/apache/build
    load sw/apache/daemon
    load sw/apache/configure

    # chown /srv (pub only)
    [[ -n $env_pub ]] && sudo chown www-data:www-data /srv -R

    # create www dir
    sudo mkdir /var/www
    sudo chown www-data:www-data /var/www -R

    echo 'Starting web server...'
    sudo apachectl restart
    sudo apachectl
}

main
