#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/apache -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    # return early when Logwatch not installed
    [[ ! -d /usr/share/logwatch ]] && return 0

    local data='https://get.webino.org/seed/data'
    if [[ ! -f /usr/share/logwatch/dist.conf/logfiles/http.conf ]]; then
        echo 'Installing Logwatch for Apache...'

        sudo wget $data/usr/share/logwatch/dist.conf/logfiles/http.conf \
            -qO /usr/share/logwatch/dist.conf/logfiles/http.conf

        sudo wget $data/usr/share/logwatch/dist.conf/logfiles/http-error.conf \
            -qO /usr/share/logwatch/dist.conf/logfiles/http-error.conf
    else
        echo 'Logwatch for Apache already installed...'
    fi
}

main
