#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Google Chrome for Selenium

main() {
    echo -e "\nGoogle Chrome install\n"

    if [[ "$(google-chrome --version 2> /dev/null)" != '' ]]; then
        echo 'Google Chrome for Selenium already installed...'
        return
    fi

    echo "Installing Google Chrome for Selenium..."
    cd /tmp

    # google chrome
    sudo apt-get install -y libxss1 libappindicator1 libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*.deb

    # selenium driver
    load devkit/chrome/selenium
}

main "$@"
