#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs Google Chrome with ChromeDriver for Selenium

load() {
    #-------------------------+
    # load remote bash source |
    #-------------------------+
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo -e "\nMachine setup for Webino™\n"

    #------+
    # init |
    #------+
    load ~lib
    load arguments "$@"

    #-------+
    # setup |
    #-------+
    load devkit/chrome/general

    #------+
    # done |
    #------+
    setup_done
}

main "$@"
