#!/bin/bash
set -e

[ "$TEST" = 'apache' ] && wget https://get.webino.org/seed/apache -qO- | sh && exit 0
[ "$TEST" = 'apache-pub' ] && wget https://get.webino.org/seed/apache -qO- | sh -s -- --pub && exit 0
[ "$TEST" = 'mysql' ] && wget https://get.webino.org/seed/mysql -qO- | sh && exit 0
[ "$TEST" = 'php' ] && wget https://get.webino.org/seed/php -qO- | sh && exit 0
[ "$TEST" = 'php7' ] && wget https://get.webino.org/seed/php -qO- | sh -s -- --pub --php 7.0.0RC5 && exit 0
[ "$TEST" = 'devkit' ] && wget https://get.webino.org/devkit -qO- | sh && exit 0
# TODO seed
#[ "$TEST" = 'seed' ] && wget https://get.webino.org/seed -qO- | sh && exit 0
# TODO easy
#[ "$TEST" = 'easy' ] && wget https://get.webino.org -qO- | sh && exit 0

if [ "$TEST" = 'dev-module' ]; then
  wget https://get.webino.org/devkit -qO- | sh
  # TODO use WebinoSkeletonModule instead
  module=WebinoDev
  git clone https://github.com/webino/${module}.git
  cd $module && webino init && webino test && webino analyze && webino api
  exit 0
fi

exit 1
