#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs dev server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo -e "\nDev server setup...\n"
    local data='@@host@@/dev-srv/~data'

    # force development environment
    _env_local=
    _env_dev=1
    _env_pub=

    # force PHP-FPM support
    php_fpm=1

    # force vhost name
    _vhost_name=dev

    # TODO??
    # setup vhost
    load vhost/dirs

    # vhost conf setup
    local file=/etc/php/fpm/pool.d/dev-srv.conf
    [[ -f $file ]] || sudo wget $data$file -qO $file

    # TODO
    # adding SFTP access for dev group
    sudo groupadd sftp-only
    # enable SFTP for sftp-only
    local is_ssh_sftp_allowed=$(grep 'AllowGroups .* sftp-only' /etc/ssh/sshd_config)
    if [[ ! $is_ssh_sftp_allowed ]]; then
        sudo sed -i -E 's/AllowGroups (.+)/AllowGroups \1 sftp-only/' /etc/ssh/sshd_config
        # TODO setup ssh sftp-only config
        wget $data'/etc/ssh/sshd_config.sftp-only' -qO- | sudo tee --append /etc/ssh/sshd_config > /dev/null
    fi

    #sudo mkdir /sftp

    # TODO decouple to script call
    #load dev-srv/user/general "$@"

    #touch $lock
    #echo -e "\nWebino™ (Dev server) configuration success...\n"

    # install general tools
    #load system/general
    #load apache/general
    #load mysql/general
    #load php/general
    #load devkit/general

    #touch $lock

    #------+
    # done |
    #------+
    echo 'Dev server setup done...'
}

main "$@"
