#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs dev server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    # lock check
    local lock=/tmp/webino.dev.general.lock
    if [[ -f $lock ]]; then
        return
    fi

    # force development environment
    _env_local=
    _env_dev=1
    _env_pub=

    # force PHP-FPM support
    php_fpm=1

    # install general tools
    load os/general
    load sw/apache
    load sw/mysql
    load sw/php
    load sw/devkit

    touch $lock
}

main "$@"
