#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs dev server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo 'Dev server setup...'
    local data='@@host@@/dev-srv/~data'

    # force development environment
    _env_local=
    _env_dev=1
    _env_pub=

    # force PHP-FPM support
    php_fpm=1

    # force vhost name
    _vhost_name=dev
    # TODO option
    _vhost_domain=dev.webino.sk

    # force dev server user name
    _dev_user_name=dev

    # setup vhost
    load vhost/dirs
    load vhost/conf
    # TODO setup vhost SSL protection with user certs

    # setup vhost.conf
    local file=/srv/dev/common.conf
    local is_vhost_configured=$(grep 'Dev server' $file)
    if [[ ! $is_vhost_configured ]]; then
        echo 'Configuring dev server vhost.conf...'
        wget $data$file -qO- | sudo tee --append $file > /dev/null
    else
        echo 'Dev server vhost.conf already configured...'
    fi

    # php-fpm dev-srv.conf setup
    local file=/etc/php/fpm/pool.d/dev-srv.conf
    [[ -f $file ]] || sudo wget $data$file -qO $file

    # adding sFTP access for dev group
    sudo groupadd sftp-only 2>/dev/null || true
    sudo mkdir -p /sftp

    # enable sFTP for sftp-only
    local is_ssh_sftp_allowed=$(grep 'AllowGroups .* sftp-only' /etc/ssh/sshd_config)
    if [[ ! $is_ssh_sftp_allowed ]]; then
        echo 'Configuring SSH sftp-only group access...'
        sudo sed -i -E 's/AllowGroups (.+)/AllowGroups \1 sftp-only/' /etc/ssh/sshd_config
        wget $data'/etc/ssh/sshd_config.sftp-only' -qO- | sudo tee --append /etc/ssh/sshd_config > /dev/null
    else
        echo 'SSH sftp-only group access already configured...'
    fi

    # TODO setup webino-devkit user
    echo 'Adding webino-devkit user...'
    sudo useradd -s /bin/bash -rUm webino-devkit

    # TODO setup authorized key for git to webino-devkit user
    # TODO setup webino-devkit
    # TODO setup webino-devkit-pro

    # setup dev server user
    load dev-srv/user/add

    #touch $lock
    #echo -e "\nWebino™ (Dev server) configuration success...\n"

    # install general tools
    #load system/general
    #load apache/general
    #load mysql/general
    #load php/general
    #load devkit/general

    #touch $lock

    #------+
    # done |
    #------+
    echo 'Dev server setup done...'
}

main "$@"
