#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Firefox for Selenium

main() {
    echo -e "\nFirefox for Selenium install...\n"

    local file=/var/lib/webino/firefox/firefox
    if [[  -f $file ]]; then
        echo 'Firefox for Selenium already installed...'
        return
    fi

    echo 'Installing Firefox for Selenium...'
    sudo mkdir -p /var/lib/webino
    cd /tmp

    wget https://ftp.mozilla.org/pub/firefox/releases/46.0.1/linux-x86_64/en-US/firefox-46.0.1.tar.bz2
    echo 'Unzipping...'
    bzip2 --version
    bzip2 -d firefox-46.0.1.tar.bz2

    echo 'Untar...'
    sudo tar -xf firefox-46.0.1.tar -C /var/lib/webino && rm firefox-46.0.1.tar & spinner $! 2>&1
    sudo chmod +x $file

    #------+
    # done |
    #------+
    echo 'Firefox for Selenium install done...'
}

main "$@"
