#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Firefox for Selenium

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo -e "\nMachine setup for Webino™ (Firefox install)...\n"

    load ~lib
    load arguments "$@"

    # Install
    load sw/firefox
}

main "$@"
