#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    wget https://get.webino.org/devkit -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It installs Google Chrome with ChromeDriver for Selenium

main() {
    load sw/php/arguments
    load sw/chrome/browser
    load sw/chrome/driver
}

main
