#!/bin/sh

# This is the Webino Seed install script!
# Copyright (c) 2015-2017 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/media -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It installs media server

wget @@host@@/seed/media/setup -qO- | bash -s -- "$@"
