#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/mysql -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It installs MySQL database

main() {
    load sw/mysql/arguments
    load sw/mysql/server
    load sw/mysql/client

    service mysql stop
    service mysql start

    # dev & pub only
    if [[ -n $env_dev || -n $env_pub ]]; then
        load sw/mysql/logwatch
    fi
}

main
