#!/bin/bash

# This is the Webino? Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/mysql -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs MySQL database

main() {
    # return early when Logwatch not installed
    [[ ! -d /usr/share/logwatch ]] && return 0

    local data='@@host@@/seed/data'
    if [[ ! -f /usr/share/logwatch/dist.conf/logfiles/mysql.conf ]]; then
        echo 'Installing Logwatch for MySQL...'

        sudo wget $data/usr/share/logwatch/dist.conf/logfiles/mysql.conf \
            -qO /usr/share/logwatch/dist.conf/logfiles/mysql.conf
    else
        echo 'Logwatch for MySQL already installed...'
    fi
}

main
