#!/bin/bash

# This is the Webino Travis support script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@

vendor/bin/coveralls -v
webino api
webino publish-gh-pages
