#!/bin/sh

echo 'Updating Ubuntu 12.04 wget to 1.14 with SNI'
wget http://ppa.launchpad.net/nathan-renniewaldock/ppa/ubuntu/pool/main/w/wget/wget_1.14-1~ppa1~precise_amd64.deb
sudo dpkg -i wget_1.14-1~ppa1~precise_amd64.deb
sudo apt-get install -f

# general
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs graphviz
sudo npm install webino-devkit -g --unsafe-perm
sudo chmod o+w /home/travis -R

[ "$BROWSER" = 'firefox' ] && wget https://get.webino.org/seed/devkit/firefox -qO- | sh
[ "$BROWSER" = 'chrome' ] && wget https://get.webino.org/seed/devkit/chrome -qO- | sh
