#!/bin/sh

echo 'Updating Ubuntu 12.04 wget to 1.14 with SNI'
wget http://ppa.launchpad.net/nathan-renniewaldock/ppa/ubuntu/pool/main/w/wget/wget_1.14-1~ppa1~precise_amd64.deb
sudo dpkg -i wget_1.14-1~ppa1~precise_amd64.deb
sudo apt-get install -f

# general
curl -sL https://deb.nodesource.com/setup | sudo bash -
sudo apt-get install -y nodejs graphviz
sudo npm install webino-devkit -g --unsafe-perm
sudo chmod o+w /home/travis -R

if [ "$BROWSER" = 'chrome' ]
then
    # google chrome
    sudo apt-get install -y libxss1 libappindicator1 libindicator7
    wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    sudo dpkg -i google-chrome*.deb
    # chromedriver
    wget -N http://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip -P /tmp
    unzip /tmp/chromedriver_linux64.zip -d /tmp
    chmod +x /tmp/chromedriver &&
    sudo mv -f /tmp/chromedriver /usr/bin/chromedriver
fi
