#!/bin/bash

# This is the Webino? Travis support script!
# Copyright (c) 2015-2017 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@

printf '\n' | pecl install -f 'mailparse-'$(php -r "echo (-1 === version_compare(phpversion(), '7.0.0') ? '2.1.6' : '3.0.2');")
(cd .. && webino init-user-cfg) &
webino update
composer require satooshi/php-coveralls:0.*
