#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/git-srv -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs Git fetch server

main() {
    cd /tmp/php

    local data='@@host@@/data/'
    local lock=git-srv.lock

    if [ ! -f $lock ]; then

        sudo useradd -r git-srv
        sudo mkdir -p /srv/git

        if [ "$(systemctl --version 2> /dev/null)" != '' ]; then
            # Systemd
            echo 'Installing Git fetch server...'
            local file=/etc/systemd/system/git-srv.service
            if [ ! -f $file ]; then
                sudo wget -qO $file $data$file
                sudo systemctl enable git-srv.service
            fi
        else
            # Upstart
            echo 'Installing Git fetch server...'
            local file=/etc/init/git-srv.conf
            if [ ! -f $file ]; then
                sudo wget -qO $file $data$file
                sudo initctl reload-configuration > /dev/null 2>&1 &
            fi
        fi

        touch $lock
    else
        echo 'Git fetch server already installed...'
    fi
}

main
