#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/satis -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Satis the Composer repository generator

main() {
    cd /opt || return
    echo -e "\nWebino Satis setup...\n"

    if [[ ! $(whereis php 2>/dev/null) ]]; then
        echo 'Satis require PHP...'
        return
    fi

    # depends on PHP version
    local satis_version;satis_version=$(php -r "echo (-1 === version_compare(phpversion(), '7.3.0') ? '3c04234b36a6de3c14d4501fcef5d33df5f1e0f2' : 'latest');")
    echo 'Version: '"$satis_version"

    sudo git clone https://github.com/composer/satis.git --depth 1
    cd satis || return

    [[ $satis_version == 'latest' ]] || git reset --hard "$satis_version"

    sudo wget https://getcomposer.org/installer -qO- | php
    sudo php composer.phar install
    sudo mkdir -p /var/satis
    sudo chown www-data:www-data /var/satis

    echo -e "\nWebino Satis setup done...\n"
}

main
