#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/satis -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Satis the Composer repository generator

main() {
    cd /opt || return
    echo -e "\nWebino Satis setup...\n"
    sudo git clone https://github.com/composer/satis.git --depth 1

    cd satis || return
    sudo wget https://getcomposer.org/installer -qO- | php
    sudo php composer.phar install
    sudo mkdir -p /var/satis
    sudo chown www-data:www-data /var/satis

    echo -e "\nWebino Satis setup done...\n"
}

main
