#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/satis -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It installs Satis the Composer repository generator

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino.tmp
    source /tmp/webino.tmp
}

main() {
    echo -e "\nInstalling Satis the Composer repository generator...\n"

    load lib/trap
    load lib/spinner
    load arguments "$@"

    # Install
    load sw/satis
}

main "$@"
