#!/bin/bash

# This is the Webino Seed install support script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)

main() {
    # defaults
    php_prefix=

    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        --php) # set PHP version
            php_version=${argv[$n]}
            shift
            shift
        ;;
        --php-prefix) # set PHP prefix
            php_prefix=${argv[$n]}
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
