#!/bin/bash

# This is the Webino? Seed install support script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04

main() {
    # defaults
    php_prefix=

    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        --php) # set PHP version
            php_version=${argv[$n]}
            shift
            shift
        ;;
        --php-prefix) # set PHP prefix
            php_prefix=${argv[$n]}
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
