#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {

    # Build IMAP
    cd /tmp/imap-2007f
    if [ ! -f built.lock ]; then
        echo 'Building IMAP...'
        make slx SSLINCLUDE=/usr/include/openssl EXTRACFLAGS=-fPIC
        mkdir lib && mkdir include
        cp c-client/*.c lib
        cp c-client/*.h include
        cp c-client/c-client.a lib/libc-client.a
        sudo cp . /usr/local/imap-2007f -R
        touch built.lock
    else
        echo 'IMAP already built...'
    fi

    local prefix=${php_prefix-'php'}

    # PHP build config
    local php_cfg="--with-config-file-path=/etc/$prefix \
            --with-config-file-scan-dir=/etc/$prefix/conf.d \
            --enable-cli \
            --with-pdo-mysql \
            --with-mysqli \
            --with-pear \
            --with-openssl
            --with-openssl-dir=/usr \
            --with-iconv \
            --with-xsl=/usr \
            --with-curl=/usr \
            --enable-mbstring \
            --enable-exif \
            --with-zlib \
            --with-zlib-dir \
            --with-gd \
            --with-jpeg-dir=/usr/lib \
            --with-gettext \
            --enable-gd-native-ttf \
            --with-freetype-dir \
            --with-mhash \
            --enable-ftp \
            --with-pspell \
            --with-mcrypt \
            --enable-calendar \
            --enable-pcntl \
            --enable-soap \
            --enable-sockets \
            --enable-wddx \
            --enable-zip \
            --without-readline \
            --with-libedit \
            --with-imap=/usr/local/imap-2007f \
            --with-kerberos \
            --with-imap-ssl \
            --enable-bcmath \
            --enable-fpm"

    # Intl support for PHP>=5.4
    php_cfg+=$(php -r "echo (-1 === version_compare('$php_version', '5.4') ? '' : ' --enable-intl');")

    # Install path prefix
    if [[ -n $php_prefix ]]; then
        echo 'With prefix: '$prefix
        php_cfg+=' --prefix=/opt/'$prefix
    else
        # Check apache
        [ "$php_apache" = on ] && echo 'With Apache...' && php_cfg+=' --with-apxs2=/usr/bin/apxs'
    fi

    # Build PHP
    cd /tmp/php
    if [ ! -f built.lock ]; then
        echo 'Building PHP...'
        sh ./buildconf --force
        sh ./configure $php_cfg
        make
        sudo make install
        touch built.lock
    else
        echo 'PHP already built...'
    fi
}

main
