#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {

    # Build IMAP
    cd /tmp/imap-2007f
    if [ ! -f builded.lock ]; then
        echo 'Building IMAP...'
        make slx SSLINCLUDE=/usr/include/openssl EXTRACFLAGS=-fPIC
        mkdir lib && mkdir include
        cp c-client/*.c lib
        cp c-client/*.h include
        cp c-client/c-client.a lib/libc-client.a
        sudo cp . /usr/local/imap-2007f -R
        touch builded.lock
    else
        echo 'IMAP already builded...'
    fi

    # PHP build config
    local php_cfg="--with-config-file-path=/etc/php \
            --with-config-file-scan-dir=/etc/php/conf.d \
            --enable-cli \
            --with-mysql \
            --with-pdo-mysql \
            --with-mysqli \
            --with-pear \
            --with-openssl \
            --with-iconv \
            --with-xsl=usr \
            --with-curl \
            --enable-mbstring \
            --enable-exif \
            --with-zlib \
            --with-zlib-dir \
            --with-gd \
            --with-jpeg-dir=/usr/lib \
            --with-gettext \
            --enable-gd-native-ttf \
            --with-freetype-dir \
            --with-mhash \
            --enable-ftp \
            --with-pspell \
            --with-mcrypt \
            --enable-calendar \
            --enable-pcntl \
            --enable-soap \
            --enable-sockets \
            --enable-wddx \
            --enable-zip \
            --without-readline \
            --with-libedit \
            --with-imap=/usr/local/imap-2007f \
            --with-kerberos \
            --with-imap-ssl \
            --enable-bcmath \
            --enable-intl \
            --enable-fpm"

    # Check apache
    [ "$php_apache" = on ] && echo 'With Apache...' && php_cfg+=' --with-apxs2=/usr/bin/apxs'

    # Build PHP
    cd /tmp/php
    if [ ! -f builded.lock ]; then
        echo 'Building PHP...'
        sh ./buildconf --force
        sh ./configure $php_cfg
        make
        sudo make install
        touch builded.lock
    else
        echo 'PHP already builded...'
    fi
}

main
