#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php

    if [ ! -f composer.lock ]; then
        echo 'Installing Composer...'
        # Install PHP composer (local|dev only)
        wget https://getcomposer.org/installer -qO- | sudo php -- --install-dir=/usr/local/bin --filename=composer
    else
        echo 'Composer already installed...'
    fi
}

main
