#!/bin/bash
func () {
    echo "Installing dependencies for PHP build..."
    sudo apt-get install -y \
        libgvc6 \
        libcurl4-openssl-dev \
        pkg-config \
        libpspell-dev \
        libicu-dev \
        libmagickwand-dev \
        libmcrypt-dev \
        libxslt-dev || true
}

func
