#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp

    # IMAP
    if [ ! -d imap-2007f ]; then
        echo 'Downloading IMAP...'
        wget ftp://ftp.cac.washington.edu/imap/imap-2007f.tar.gz \
            -O imap-2007f.tar.gz && tar xvf imap-2007f.tar.gz & spinner $! && rm imap-2007f.tar.gz 2>&1
    else
        echo 'IMAP already downloaded...'
    fi

    # PHP
    if [ ! -d php ]; then
        echo 'Downloading PHP...'
        wget 'https://github.com/php/php-src/archive/php-'$php_version'.tar.gz' \
            -O php.tar.gz && tar xvf php.tar.gz & spinner $! && rm php.tar.gz && mv 'php-src-php-'$php_version php 2>&1
    else
        echo 'PHP already downloaded...'
    fi
}

main
