#!/bin/bash

# This is the Webino? Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    # return early when File2ban not installed
    [[ ! -f /etc/fail2ban/jail.local ]] && return 0

    local data='@@host@@/seed/data'
    local is_configured=$(grep php /etc/fail2ban/jail.local)

    if [[ -z "$is_configured" ]]; then
        echo 'Installing Fail2ban for PHP...'

        echo "$(wget $data/etc/fail2ban/jail.local-php -qO-)" | \
            sudo tee --append /etc/fail2ban/jail.local > /dev/null

        sudo service fail2ban restart
    else
        echo 'Fail2ban for PHP already installed...'
    fi
}

main
