#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php

    if [ ! -f imagick.lock ]; then
        echo 'Installing ImageMagick...'
        # non-interactive
        printf '\n' | sudo pecl install -f imagick
        touch imagick.lock
    else
        echo 'ImageMagick already installed...'
    fi

    # configuring
    local etc='/etc/php5'
    local is_configured=$(grep imagick.so $etc/php.ini)
    if [ "$is_configured" == "" ]; then
        echo 'Enabling PHP Imagick module" ...'
        echo "extension=imagick.so" | cat - $etc/php.ini | sudo tee $etc/php.ini > /dev/null
    fi
    local is_configured_cli=$(grep imagick.so $etc/php-cli.ini)
    if [ "$is_configured_cli" == "" ]; then
        echo 'Enabling PHP-CLI Imagick module" ...'
        echo "extension=imagick.so" | cat - $etc/php-cli.ini | sudo tee $etc/php-cli.ini > /dev/null
    fi
}

main
