#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {
    load sw/php/arguments

    # resolve latest version
    php_version_latest=$(echo $(wget -qO- http://php.net/downloads.php \
        | grep -Pozm 1 'Current Stable.*\n*.*PHP [0-9]+\.[0-9]+\.[0-9]+' | grep -Eom 1 '[0-9\.]+'))

    php_version=${php_version-$php_version_latest}

    [[ "$(whereis apachectl)" == *"/apachectl"* ]] && php_apache=on || php_apache=off

    # update PHP build
    [[ -n $update ]] && load sw/php/clean

    # clean PHP build
    [[ -n $clean ]] && load sw/php/clean && return

    echo 'Seeding PHP '$php_version

    load sw/php/dependencies
    load sw/php/download
    load sw/php/build
    load sw/php/configure

    # configure local development environment
    #[[ -z $update ]] && [[ $ENVIRONMENT == 'local' ]] && source $1/php.d/configure-local-dev # TODO
    #[[ $ENVIRONMENT == 'local' ]] && source $1/php.d/php-qa # TODO

    # TODO
    # local & dev only
    if [[ -n $env_local || -n $env_dev ]]; then
        load sw/php/xdebug
        load sw/php/mailparse
        #load sw/php/profiler #TODO profiler
        load sw/php/composer
    fi

    load sw/php/imagick
    load sw/php/memcache
    load sw/php/opcache

    if [ "$php_apache" = on ]; then
        echo 'Restarting web server...'
        sudo apachectl stop
        sudo apachectl start
    fi

    # dev & pub only
    if [[ -n $env_dev || -n $env_pub ]]; then
        load sw/php/logwatch
        load sw/php/fail2ban
    fi
}

main
