#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {
    # return early when Logwatch not installed
    [[ ! -d /usr/share/logwatch ]] && return 0

    local data='https://get.webino.org/seed/data'
    if [[ ! -f /usr/share/logwatch/dist.conf/logfiles/php.conf ]]; then
        echo 'Installing Logwatch for PHP...'

        sudo wget $data/usr/share/logwatch/dist.conf/logfiles/php.conf \
            -qO /usr/share/logwatch/dist.conf/logfiles/php.conf
    else
        echo 'Logwatch for PHP already installed...'
    fi
}

main
