#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php

    if [ ! -f memcache.lock ]; then
        echo 'Installing Memcache...'
        # non-interactive
        printf '\n' | sudo pecl install -f memcache
        touch memcache.lock
    else
        echo 'Memcache already installed...'
    fi
}

main
