#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

#
# TODO!!!
#

main() {
    cd /tmp/php

    if [ ! -f php-fpm.lock ]; then

        if [ "$(systemctl --version 2> /dev/null)" != '' ]; then
            # Systemd
            echo 'Installing PHP-FPM Systemd service...'
            if [ ! -f /lib/systemd/system/php-fpm.service ]; then
                sudo wget -qO /lib/systemd/system/php-fpm.service @@host@@/seed/data/lib/systemd/system/php-fpm.service
            fi

            sudo systemctl enable php-fpm.service

        else
            # Upstart
            echo 'Installing PHP-FPM Upstart daemon...'
            if [ ! -f /etc/init/php-fpm.conf ]; then
                sudo wget -qO /etc/init/php-fpm.conf @@host@@/seed/data/etc/init/php-fpm.conf
            fi
        fi

        sudo phpfpm start
        touch php-fpm.lock
    else
        echo 'PHP-FPM upstart daemon already installed...'
    fi
}

main
