#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It builds PHP from source

#
# TODO!!!
#

main() {
    cd /tmp/php

    if [ ! -f php-fpm.lock ]; then
        echo 'Installing PHP-FPM upstart daemon...'
        if [ ! -f /etc/init/php-fpm.conf ]; then
            sudo wget -qO /etc/init/php-fpm.conf https://get.webino.org/seed/data/etc/init/php-fpm.conf
        fi

        sudo phpfpm start
        touch php-fpm.lock
    else
        echo 'PHP-FPM upstart daemon already installed...'
    fi
}

main
