#!/bin/bash

# This is the Webino? Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/php -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php

    if [ ! -f profiler.lock ]; then
        echo 'Installing Profiler [TODO]...'
        # TODO use blackfire
        touch profiler.lock
    else
        echo 'Profiler already installed...'
    fi

    # TODO add profiler extension to php.ini
}

main
