#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php

    if [ ! -f xdebug.lock ]; then
        echo 'Installing Xdebug...'
        # non-interactive
        printf '\n' | sudo pecl install -f xdebug
        touch xdebug.lock
    else
        echo 'Xdebug already installed...'
    fi
    
    # configuring
    local etc='/etc/php'
    local is_configured=$(grep xdebug.so $etc/php.ini)
    if [ "$is_configured" == "" ]; then
        echo 'Enabling PHP Xdebug module...'
        echo "zend_extension=xdebug.so" | cat - $etc/php.ini | sudo tee $etc/php.ini > /dev/null
    fi
}

main
