#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/vhost -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It creates a virtual host

main() {
    #------------------+
    # vhost conf setup |
    #------------------+
    local data='@@host@@/vhost/~data'
    local dir='/srv/'$_vhost_name

    local src=/srv/example/common.conf
    local dest=$dir'/common.conf'
    [[ -f $dest ]] || sudo wget $data$src -qO $dest

    local src=/srv/example/http.conf
    local dest=$dir'/http.conf'
    [[ -f $dest ]] || sudo wget $data$src -qO $dest

    local src=/srv/example/https.conf
    local dest=$dir'/https.conf'
    [[ -f $dest ]] || sudo wget $data$src -qO $dest

    local src=/srv/example/vhost.conf
    local dest=$dir'/vhost.conf'
    [[ -f $dest ]] || sudo wget $data$src -qO $dest

    # TODO
    # with webino support toggle
    # allow override toggle support
    # _vhost_www support
    # HTTP enabled toggle support
    # HTTPS setup support

    #-------------------------+
    # replace vars in configs |
    #-------------------------+
    sudo find $dir -type f -exec sed -i 's/%VHOST_NAME%/'$_vhost_name'/g' {} \;
    sudo find $dir -type f -exec sed -i 's/%VHOST_DOMAIN%/'$_vhost_domain'/g' {} \;
}

main "$@"
