#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/vhost -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It creates a virtual host

main() {
    #-------------------+
    # vhost directories |
    #-------------------+
    local dir='/srv/'$_vhost_name
    sudo mkdir -p $dir'/public'
    sudo mkdir -p $dir'/log'
    sudo mkdir -p $dir'/tmp'
    sudo chown www-data:www-data -R $dir
}

main "$@"
