#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/sftp-user -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It creates a SFTP user account

main() {
    #------+
    # init |
    #------+
    load sftp-user/arguments "$@"

    #-------+
    # setup |
    #-------+
    if [[ ! $_sftp_user_name ]];then
        return
    fi

    echo -e "\nSFTP '$_sftp_user_name' user setup...\n"

    # adding SFTP user group
    load sftp-user/group

    # check user exists
    if [[ $(id $_sftp_user_name 2> /dev/null) ]]; then
        echo 'User already exists...'
        return
    fi

    # create user account
    sudo useradd -m $_sftp_user_name
    sudo usermod -aG sftp-only $_sftp_user_name

    # set optional user group
    if [[ $_sftp_user_group ]]; then
        echo "Adding user to optional group '$_sftp_user_group'..."
        sudo groupadd $_sftp_user_group &> /dev/null || true
        sudo usermod -aG $_sftp_user_group $_sftp_user_name
    fi

    # add user authorized key
    if [[ ! $_no_interaction ]]; then
        echo 'User SSH authorized key:'
        read sftp_user_authorized_key </dev/tty

        #[[ -n "$sftp_user_authorized_key" ]] && \
            sudo su $_sftp_user_name -c 'mkdir -p ~/.ssh; printf '$sftp_user_authorized_key' | tee -a ~/.ssh/authorized_keys > /dev/null'
    fi

    #------+
    # done |
    #------+
    load sftp-user/done
}

main "$@"
