#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/sftp-user -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It creates a SFTP user account

main() {
    echo -e "\nVirtual host setup...\n"

    #------+
    # init |
    #------+
    load sftp-user/arguments "$@"

    #-------+
    # setup |
    #-------+
    # TODO
    #load sftp-user/configure

    if [[ ! $_sftp_user_name ]];then
        return
    fi

    # TODO add user if
    sudo groupadd sftp-only &> /dev/null

    # TODO create user account
    sudo useradd -m $_sftp_user_name
    sudo usermod -aG sftp-only $_sftp_user_name
    if [[ $_sftp_user_group ]]; then
        sudo groupadd $_sftp_user_group &> /dev/null
        sudo usermod -aG $_sftp_user_group _sftp_user_name
    fi

    # TODO add user authorized key
    if [[ ! $_no_interaction ]]; then
        echo 'User SSH authorized key:'
        read sftp_user_authorized_key </dev/tty

        [[ -n "$sftp_user_authorized_key" ]] && \
            sudo su $_sftp_user_name -c "mkdir -p ~/.ssh && printf "$sftp_user_authorized_key" | tee ~/.ssh/authorized_keys > /dev/null"
    fi

    #------+
    # done |
    #------+
    load sftp-user/done
}

main "$@"
