#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/sftp-user -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It creates a SFTP user account

main() {
    echo 'Adding SFTP user group...'
    local data='@@host@@/dev-srv/~data'
    local config='/etc/ssh/sshd_config'

    sudo groupadd sftp-only 2>/dev/null || true
    sudo mkdir -p /sftp || true

    # enable SFTP for sftp-only
    sudo sed -i -E 's/AllowGroups (.+)/AllowGroups \1 sftp-only/' $config
    sudo sed -i 's~Subsystem sftp /usr/lib/openssh/sftp-server~Subsystem sftp internal-sftp~' $config

    local is_ssh_sftp_allowed=$(grep 'Match Group sftp-only' $config)
    if [[ ! $is_ssh_sftp_allowed ]]; then
        echo 'Configuring SSH sftp-only group access...'
        wget $data'/etc/ssh/sshd_config.sftp-only' -qO- | sudo tee --append $config > /dev/null
    else
        echo 'SSH sftp-only group access already configured...'
    fi
}

main "$@"
