#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    wget https://get.webino.org/devkit -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It installs Firefox for Selenium

main() {
    load sw/php/arguments

    cd /tmp
    local lock=seed.sw.firefox.lock

    if [[ ! -f $lock ]]; then
        echo "Installing Firefox for Selenium..."
        sudo mkdir -p /var/lib/webino

        wget https://ftp.mozilla.org/pub/firefox/releases/46.0.1/linux-x86_64/en-US/firefox-46.0.1.tar.bz2 \
             && bzip2 -d firefox-46.0.1.tar.bz2 & spinner $! 2>&1

        sudo tar -xf firefox-46.0.1.tar -C /var/lib/webino && rm firefox-46.0.1.tar & spinner $! 2>&1
        sudo chmod +x /var/lib/webino/firefox/firefox

        touch $lock
    else
        echo 'Firefox for Selenium already installed...'
    fi
}

main
