#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {

    # Build IMAP
    cd /tmp/imap-2007f
    local lock=built.lock

    if [ ! -f $lock ]; then
        echo 'Building IMAP...'
        make slx SSLINCLUDE=/usr/include/openssl EXTRACFLAGS=-fPIC
        mkdir lib && mkdir include
        cp c-client/*.c lib
        cp c-client/*.h include
        cp c-client/c-client.a lib/libc-client.a
        sudo cp . /usr/local/imap-2007f -R
        touch $lock
    else
        echo 'IMAP already built...'
    fi


    # PHP build config
    local prefix='/'${php_prefix:-'php'}
    local php_cfg="--with-config-file-path=/etc$prefix \
            --with-config-file-scan-dir=/etc$prefix/conf.d \
            --enable-cli \
            --enable-calendar \
            --enable-pcntl \
            --enable-soap \
            --enable-zip \
            --enable-bcmath \
            --enable-exif \
            --enable-gd-native-ttf \
            --enable-mbstring \
            --with-gd \
            --with-pear \
            --with-zlib \
            --with-zlib-dir \
            --with-iconv \
            --with-pdo-mysql \
            --with-gettext \
            --with-mhash \
            --with-pspell \
            --with-libedit \
            --with-kerberos \
            --with-imap \
            --with-imap-ssl \
            --with-xsl=/usr \
            --with-curl=/usr \
            --with-jpeg-dir=/usr/lib \
            --with-freetype-dir \
            --without-readline"

    # TODO PHP 5.3 support
    # TODO PHP 5.6 support

    # TODO not with PHP 7.1
    # deprecated
    # --with-mcrypt \
    # --with-mysqli \

    # TODO not with Ubuntu 16.04 and PHP 5.3!!!
    # --enable-ftp \
    # --with-openssl \
    # --with-openssl-dir=/usr \

    # TODO not with Ubuntu 16.04 and 5.6
    # --enable-wddx \
    # --enable-sockets \

    # Intl support for PHP>=5.4
    sudo dpkg --compare-versions "$php_version" 'lt' '5.4' || {
       echo 'With INTL support...'
       php_cfg+=' --enable-intl'
    }

    # Install path prefix
    if [[ -n $php_prefix ]]; then
        echo 'With prefix: '$prefix
        php_cfg+=' --prefix=/opt'$prefix
    else
        # Check Apache
        [ "$php_apache" = on ] && echo 'With Apache...' && php_cfg+=' --with-apxs2=/usr/bin/apxs'
    fi

    # PHP-FPM support
    if [[ -n $php_fpm ]]; then
        echo 'With PHP-FPM support...'
        php_cfg+=' --enable-fpm'
    fi

    # Build PHP
    cd /tmp/php
    local lock=built.lock
    if [ ! -f $lock ]; then
        echo 'Building PHP...'
        sh ./buildconf --force
        sh ./configure $php_cfg
        make
        sudo make install
        touch $lock
    else
        echo 'PHP already built...'
    fi
}

main
