#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp

    if [[ ! -f php.dependencies.lock ]]; then
        echo "Installing dependencies for PHP build..."

        sudo apt-get install -y \
            re2c \
            libcurl4-openssl-dev \
            pkg-config \
            libpspell-dev \
            libicu-dev \
            libedit-dev \
            libmagickwand-dev \
            libmcrypt-dev \
            libxslt1-dev \
            libc-client-dev \
            libkrb5-dev

        # bison
        sudo apt-get purge -y bison
        sudo wget http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb
        sudo wget http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb
        sudo dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb
        sudo dpkg -i bison_2.7.1.dfsg-1_amd64.deb

        touch php.dependencies.lock
    else
        echo 'Dependencies for PHP build already installed...'
    fi
}

main
