#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp

    # IMAP
    if [ ! -d imap-2007f ]; then
        echo 'Downloading IMAP...'
        wget https://media.webino.sk/support/imap/imap-2007f.tar.gz \
            -O imap-2007f.tar.gz && tar xvf imap-2007f.tar.gz & spinner $! && rm imap-2007f.tar.gz 2>&1
    else
        echo 'IMAP already downloaded...'
    fi

    # PHP
    if [ ! -d php ]; then
        echo 'Downloading PHP '$_php_version'...'
        wget 'https://github.com/php/php-src/archive/php-'$_php_version'.tar.gz' \
            -O php.tar.gz && tar xvf php.tar.gz & spinner $! && rm php.tar.gz && mv 'php-src-php-'$_php_version php 2>&1
    else
        echo 'PHP already downloaded...'
    fi
}

main
