#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    load sw/php/arguments "$@"

    # resolve latest version
    php_version_latest=$(echo $(wget -qO- http://php.net/downloads.php \
        | grep -a -Pozm 1 'Current Stable.*\n*.*PHP [0-9]+\.[0-9]+\.[0-9]+' | grep -a -Eom 1 '[0-9\.]+'))

    php_version=${php_version-$php_version_latest}

    [[ "$(whereis apachectl)" == *"/apachectl"* ]] && php_apache=on || php_apache=off

    # update PHP build
    [[ -n $_update ]] && load sw/php/clean

    # clean PHP build
    [[ -n $_clean ]] && load sw/php/clean && return

    echo 'Installing PHP '$php_version

    load sw/php/dependencies
    load sw/php/download
    load sw/php/build
    load sw/php/configure

    # configure local development environment
    #[[ -z $_update ]] && [[ $ENVIRONMENT == 'local' ]] && source $1/php.d/configure-local-dev # TODO
    #[[ $ENVIRONMENT == 'local' ]] && source $1/php.d/php-qa # TODO

    # TODO
    # local & dev only
    if [[ -n $_env_local || -n $_env_dev ]]; then
        load sw/php/xdebug
        load sw/php/mailparse
        #load sw/php/profiler #TODO profiler
        load sw/php/composer
    fi

    # install PHP-FPM support
    if [[ -n $php_prefix ]]; then
        load sw/php/php-fpm

    # install extra if empty prefix
    else
        load sw/php/opcache
        load sw/php/imagick
        #load sw/php/memcache #TODO memcache
    fi

    # web server restart
    if [ "$php_apache" = on ]; then
        echo 'Restarting web server...'
        sudo apachectl restart > /dev/null 2>&1 &
    fi

    # dev & pub only
    if [[ -n $_env_dev || -n $_env_pub ]]; then
        load sw/php/logwatch
        load sw/php/fail2ban
    fi
}

main "$@"
