#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php
    local etc='/etc/'${php_prefix:-'php'}
    local data='@@host@@/data/'
    local lock=php-fpm.lock

    if [ ! -f $lock ]; then

        echo 'Installing PHP-FPM support...'
        local file=/usr/sbin/php-fpm
        echo "$(wget $data$file -qO- | sed s/'%PREFIX%'/$_php_prefix/g | sudo tee $file > /dev/null

        if [ "$(systemctl --version 2> /dev/null)" != '' ]; then
            # Systemd
            echo 'Installing PHP-FPM Systemd service...'
            local file=/etc/systemd/system/php-fpm.service
            if [ ! -f $file ]; then
                sudo wget $data$file -qO $file
                sudo systemctl enable php-fpm.service
            fi
        else
            # Upstart
            echo 'Installing PHP-FPM Upstart daemon...'
            local file=/etc/init/php-fpm.conf
            if [ ! -f $file ]; then
                sudo wget $data$file -qO $file
                sudo initctl reload-configuration > /dev/null 2>&1 &
            fi
        fi

        # setup apache PHP-FPM support config
        local file=/etc/apache2/conf.d/php-fpm.conf
        sudo wget $data$file -qO $file

        # setup PHP-FPM config
        [[ -d $etc/fpm ]] || mkdir -p $etc/fpm/pool.d
        local file=/fpm/php-fpm.conf
        [[ -f $etc$file ]] || sudo wget $data'/php'$file -qO $etc$file

        # start PHP-FPM
        echo 'Starting PHP-FPM...'
        sudo /usr/sbin/php-fpm start > /dev/null 2>&1 &
        touch $lock
    else
        echo 'PHP-FPM support already installed...'
    fi
}

main
