#!/bin/bash

# This is the Webino™ Seed install script!
# Copyright (c) 2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/seed/git-srv -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs Git fetch server

main() {
    cd /tmp/php

    if [ ! -f git-srv.lock ]; then

        useradd -r git-srv
        mkdir -p /srv/git

        if [ "$(systemctl --version 2> /dev/null)" != '' ]; then
            # Systemd
            echo 'Installing Git fetch server...'
            if [ ! -f /etc/systemd/system/git-srv.service ]; then
                sudo wget -qO /etc/systemd/system/git-srv.service @@host@@/seed/data/etc/systemd/system/git-srv.service
                sudo systemctl enable git-srv.service
            fi
        else
            # Upstart
            echo 'Installing Git fetch server...'
            if [ ! -f /etc/init/git-srv.conf ]; then
                sudo wget -qO /etc/init/git-srv.conf @@host@@/seed/data/etc/init/git-srv.conf
            fi
        fi

        touch git-srv.lock
    else
        echo 'Git fetch server already installed...'
    fi
}

main
