#!/bin/bash

# This is the Webino™ Seed install script!
# Copyright (c) 2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino™ Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/certbot -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs Let’s Encrypt certificate bot

load() {
    # Load remote bash source
    wget -qO /tmp/seed.tmp @@host@@/seed/$1
    source /tmp/seed.tmp
}

main() {
    echo -e "\nInstalling Let’s Encrypt compatible certificate bot...\n"

    load lib/trap.lib
    load lib/spinner.lib
    load arguments "$@"

    # Install
    load sw/certbot
}

main "$@"
