#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp/httpd

    local data='@@host@@/data/'
    local lock=daemon.lock

    if [ ! -f $lock ]; then

        if [ "$(systemctl --version 2> /dev/null)" != '' ]; then
            # Systemd
            echo 'Installing Apache Systemd service...'
            local file=/etc/systemd/system/httpd.service
            if [ ! -f $file ]; then
                sudo wget -qO $file $data$file
                sudo systemctl enable httpd.service > /dev/null 2>&1 &
            fi
        else
            # Upstart
            echo 'Installing Apache upstart daemon...'
            local file=/etc/init/httpd.conf
            if [ ! -f $file ]; then
                sudo wget -qO $file $data$file
                sudo initctl reload-configuration > /dev/null 2>&1 &
            fi
        fi

        touch $lock
    else
        echo 'Upstart daemon already installed...'
    fi
}

main
