#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp

    # Apache
    if [ ! -d httpd ]; then
        echo 'Downloading Apache... '$apache_version
        wget 'http://tux.rainside.sk/apache/httpd/httpd-'$apache_version'.tar.gz' \
            -qO httpd.tar.gz && tar xvf httpd.tar.gz & spinner $! && rm httpd.tar.gz 2>&1

        mv httpd-* httpd
        cd httpd

        # Apache APR
        echo 'Downloading Apache APR... '$apache_apr_version
        wget 'http://archive.apache.org/dist/apr/apr-'$apache_apr_version'.tar.gz' \
            -qO apr.tar.gz && tar xvf apr.tar.gz & spinner $! && rm apr.tar.gz 2>&1

        mv 'apr-'$apache_apr_version srclib/apr

        # Apache APR Util
        echo 'Downloading Apache APR Util... '$apache_apr_util_version
        wget 'http://archive.apache.org/dist/apr/apr-util-'$apache_apr_util_version'.tar.gz' \
            -qO apr-util.tar.gz && tar xvf apr-util.tar.gz & spinner $! && rm apr-util.tar.gz 2>&1

        mv 'apr-util-'$apache_apr_util_version srclib/apr-util
    else
        echo 'Apache already downloaded...'
    fi
}

main
