#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04
#
# What this script does?
#   - It builds Apache from source

main() {
    local lock=/tmp/webino.sw.apache.purge.lock

    if [ ! -f $lock ]; then
        echo 'Removing pre-installed Apache...'

        sudo apt-get purge -y apache*
        sudo apt-get autoremove -y

        touch $lock
    else
        echo 'Pre-installed Apache already removed...'
    fi
}

main
