#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It install general OS tools

main() {
    # exit early on clean
    [[ -n $clean ]] && return

    # resolve server info
    if [[ -n $env_dev || -n $env_pub ]]; then
        # (dev|pub only)
        host_ip=$(ip addr | grep "scope global" | grep -Po "([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)" | head -1)
        host_name=$(cat /etc/hosts | grep $host_ip | awk -F' ' '{print $2}' | awk '{print $1}' | tr . -)
    else
        host_ip=127.0.0.1
        host_name=webino.local
    fi

    admin_mail=${admin_mail-'admin@'$host_name}

    load os/arguments

    local lock=/tmp/seed.os.general.lock

    if [[ ! -f $lock ]]; then
        echo 'Installing general tools...'

        sudo apt-get clean
        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            libpcre3-dev \
            libwww-perl \
            libssl-dev \
            libkrb5-dev \
            debconf-utils \
            autoconf \
            curl \
            git

        # auto-updates (dev|pub only)
        [[ -n $env_dev || -n $env_pub ]] && sudo apt-get install -y cron-apt

        touch $lock
    else
        echo 'General tools already installed...'
    fi

    load os/locale

    # (dev|pub only)
    if [[ -n $env_dev || -n $env_pub ]]; then
        load os/mailer
        load os/secure
    fi
}

main
