#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It install general OS tools

main() {
    # exit early on clean
    [[ -n $clean ]] && return


    local lock=/tmp/seed.os.general.lock

    if [[ ! -f $lock ]]; then
        echo 'Installing general tools...'

        sudo apt-get update
        sudo apt-get install -y \
            build-essential \
            libpcre3-dev \
            libwww-perl \
            libssl-dev \
            debconf-utils \
            autoconf \
            curl \
            git

        # Install PHP composer (local|dev only)
        [[ -n $env_local || -n $env_dev ]] && \
            wget https://getcomposer.org/installer -qO- | sudo php -- --install-dir=/usr/local/bin --filename=composer

        touch $lock
    else
        echo 'General tools already installed...'
    fi
}

main
