#!/bin/sh

# This is the Webino? Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino? Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed/os -qO- | sh
#
# Webino? currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04

wget @@host@@/seed/os/setup -qO- | bash -s -- "$@"
