#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It fixes locale

main() {
    # exit early on clean
    [[ -n $clean ]] && return


    local lock=/tmp/seed.os.locale.lock

    if [[ ! -f $lock ]]; then
        echo 'Setting locale...'

        sudo locale-gen en_US.UTF-8
        sudo locale-gen sk_SK.UTF-8
        sudo dpkg-reconfigure locales
        sudo update-locale

        touch $lock
    else
        echo 'Locale already set...'
    fi
}

main
