#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget @@host@@/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It installs system mailer

main() {
    # exit early on clean
    [[ -n $clean ]] && return

    # return early on no settings
    [[ -z "${smtp_host-}" || -z "${smtp_user-}" ]] && return

    local lock=/tmp/seed.os.mailer.lock

    if [[ ! -f $lock ]]; then
        echo 'Installing mailer...'

        if [[ -z "${smtp_password-}" ]]; then
            echo 'SMTP mailer password:'
            read -s smtp_password </dev/tty
        fi

        # remove pre-installed mailer
        sudo apt-get purge -y postfix* sendmail* exim*
        sudo apt-get autoremove -y

        # install mailer
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y nullmailer

        # configure mailer
        echo "$smtp_host smtp --insecure --port=587 --starttls --user=$smtp_user --pass=$smtp_password" | \
            sudo tee /etc/nullmailer/remotes > /dev/null

        echo $host_name | sudo tee /etc/nullmailer/defaultdomain > /dev/null
        echo $admin_mail | sudo tee /etc/nullmailer/adminaddr > /dev/null
        echo $admin_mail | sudo tee /etc/nullmailer/forced-from > /dev/null
        echo $host_name | sudo tee /etc/nullmailer/me > /dev/null

        service nullmailer reload

        touch $lock
    else
        echo 'Mailer already installed...'
    fi
}

main
