#!/bin/bash

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 12.04 (wget 1.14)
#   - Ubuntu 14.04
#
# What this script does?
#   - It secures the operating system

main() {
    # exit early on clean
    [[ -n $clean ]] && return


    local lock=/tmp/seed.os.secure.lock

    if [[ ! -f $lock ]]; then
        echo 'Securing operating system...'

        echo 'Securing SSH...'

        # allow only root login
        local is_ssh_root_only=$(grep "AllowUsers root" /etc/ssh/sshd_config)
        if [[ -z "$is_ssh_root_only" ]]; then
            echo 'Enabling SSH for root user only ...'
            echo "AllowUsers root" | cat - /etc/ssh/sshd_config | sudo tee /etc/ssh/sshd_config > /dev/null
        fi

        # change port
        local ssh_port='22'$(echo $(< /dev/urandom tr -dc 0-9 | head -c2))
        sudo sed -i 's/Port .*/Port '$ssh_port'/' /etc/ssh/sshd_config
        echo 'New SSH port: '$ssh_port

        # add root ssh key
        if [[ -z "$no_interaction" ]]; then
            echo 'Root SSH authorized key:'
            read rootSshAuthorizedKey </dev/tty

            [[ -n "$rootSshAuthorizedKey" ]] && \
                sudo mkdir -p ~/.ssh && echo $rootSshAuthorizedKey | sudo tee ~/.ssh/authorized_keys > /dev/null
        fi

        # disable password
        sudo sed -i 's/PermitRootLogin yes/PermitRootLogin without-password/' /etc/ssh/sshd_config
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
        sudo sed -i 's/UsePAM yes/UsePAM no/' /etc/ssh/sshd_config

        service ssh restart

        # apticron
        echo 'Installing apticron...'
        sudo apt-get install -y apticron

        sudo sed -i 's/EMAIL="root"/EMAIL="'$admin_mail'"/' /etc/apticron/apticron.conf
        sudo sed -i 's/# CUSTOM_FROM=""/CUSTOM_FROM="'$admin_mail'"/' /etc/apticron/apticron.conf
        sudo sed -i 's/# SYSTEM="foobar.example.com"/SYSTEM="'$host_name'"/' /etc/apticron/apticron.conf

        # logwatch
        echo 'Installing logwatch...'
        sudo apt-get install -y logwatch

        echo "
        TmpDir=/tmp
        HostName=$host_name
        Format=html
        Output=mail
        Detail=High
        MailFrom=$admin_mail
        MailTo=$admin_mail
        " | sudo tee /usr/share/logwatch/dist.conf/logwatch.conf > /dev/null

        # fail2ban
        echo 'Installing fail2ban...'
        sudo apt-get install -y fail2ban
        echo "
        [DEFAULT]
        destemail=$admin_mail
        sendername=$admin_mail
        bantime=3600
        findtime=3600
        maxretry=3
        [ssh-ddos]
        enabled=true
        [ssh-route]
        enabled=true
        [apache]
        enabled=true
        logpath=/var/log/apache*/error.log,/srv/*/log*/error.log
        [apache-multiport]
        enabled=true
        logpath=/var/log/apache*/error.log,/srv/*/log*/error.log
        [apache-noscript]
        enabled=true
        logpath=/var/log/apache*/error.log,/srv/*/log*/error.log
        [apache-overflows]
        enabled=true
        logpath=/var/log/apache*/error.log,/srv/*/log*/error.log
        [mysqld-auth]
        enabled=true
        [php-url-fopen]
        enabled=true
        logpath=/var/log/apache*/access.log,/srv/*/log*/access.log
        " | sudo tee /etc/fail2ban/jail.local > /dev/null

        sudo service fail2ban stop
        sudo service fail2ban start

        touch $lock
    else
        echo 'Operating system already secured...'
    fi
}

main
