#!/bin/sh

# This is the Webino Seed install script!
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to run Webino Seed?
# Just open up your terminal and type:
#
#    wget https://get.webino.org/seed/php -qO - | sh
#
# Webino currently supports:
#   - Linux: Ubuntu 12.04, 14.04
#
# What this script does?
#   - It builds PHP from source

wget https://get.webino.org/seed/php/setup -qO - | bash
