#!/bin/bash

load() {
    # Load remote bash source
    echo "Debug: "$1
    echo "debug -----------------------------"
    # TODO
    wget -O /tmp/seed.tmp https://get.webino.org/seed/$1 --no-check-certificate #--ca-directory=/etc/ssl/certs/
    source /tmp/seed.tmp
    cat /tmp/seed.tmp
}

main() {
    echo -e "\nMachine seed for Webino™ (PHP build)...\n"

    load lib/trap.lib
    load lib/spinner.lib
    # Install
    load os/general
    load sw/php
}

main
