#!/bin/bash

load() {
    # Load remote bash source
    echo "Debug: "$1
    curl https://get.webino.org/seed/$1
    echo "debug -----------------------------"
    wget -O /tmp/seed.tmp https://get.webino.org/seed/$1 --max-redirect=100
    #curl -sLo /tmp/seed.tmp https://get.webino.org/seed/$1
    source /tmp/seed.tmp
    cat /tmp/seed.tmp
}

main() {
    echo -e "\nMachine seed for Webino™ (PHP build)...\n"

    load lib/trap.lib
    load lib/spinner.lib
    echo "debug -----------------------------"
    # Install
    load os/general
    load sw/php
}

main
