#!/bin/bash

load() {
    # Load remote bash source
    wget -qO /tmp/seed.tmp https://get.webino.org/seed/$1
    source /tmp/seed.tmp
    echo /tmp/seed.tmp
}

main() {
    echo -e "\nMachine seed for Webino™ (PHP build)...\n"

    load lib/trap.lib
    load lib/spinner.lib
    echo "debug -----------------------------"
    # Install
    load os/general
    load sw/php
}

main
