#!/bin/bash

# This is the Webino™ Seed install script!
# Copyright (c) 2015-2017 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs Webino™ Development Kit

main() {
    # local & dev only
    if [[ -n $env_local || -n $env_dev ]]; then
        echo 'Installing WebinoDevkit™...'
        wget @@host@@/devkit -qO- | sh
    fi
}

main
