#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/media-srv -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs media server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo -e "\nMachine setup for Webino™ (Media server)...\n"

    #------+
    # init |
    #------+
    load ~lib
    load arguments "$@"

    # Force production environment
    _env_local=
    _env_dev=
    _env_pub=1

    #-------+
    # setup |
    #-------+
    load system/general
    load apache/general
    load php/general
    load git-srv/fetch
    load satis/general

    #------+
    # done |
    #------+
    setup_done
}

main "$@"
