#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2015-2016 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It installs Firefox for Selenium

load() {
    # Load remote bash source
    wget -qO /tmp/seed.tmp @@host@@/seed/$1
    source /tmp/seed.tmp
}

main() {
    echo -e "\nMachine seed for Webino™ (Firefox install)...\n"

    load lib/trap.lib
    load lib/spinner.lib
    load arguments "$@"

    # Install
    load sw/firefox
}

main "$@"
