#!/bin/sh

# This is the Webino™ Devkit install script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ Devkit currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# Dependencies:
#   - Node.js
#   - PHP >= 7.1
#   - Git, Gitflow
#   - Graphviz
#   - Firefox 46.0.1
#
# What this script does?
#   - It installs Webino™ devkit dependencies
#   - It installs Webino™ devkit via npm globally

main() {
    #----------------+
    # local|dev only |
    #----------------+
    if [[ ! $_env_local && ! $_env_dev ]]; then
        return
    fi

    echo -e "\nWebino™ devkit install...\n"

    local apt_install=""
    # Check Git
    [ "$(git --version 2>/dev/null)" = '' ] && apt_install="$apt_install git"
    # Check Gitflow
    [ "$(git flow 2>/dev/null)" = '' ] && apt_install="$apt_install git-flow"
    # Check Graphviz
    [ "$(dpkg -s graphviz 2>/dev/null)" = '' ] && apt_install="$apt_install graphviz"
    # Check Xvfb
    [ "$(which Xvfb 2>/dev/null)" = '' ] && apt_install="$apt_install xvfb xfonts-cyrillic"
    # Check Firefox
    [ "$(firefox -v 2>/dev/null)" = '' ] && apt_install="$apt_install firefox"

    # Install apt-get packages
    if [ "$apt_install" != "" ]
    then
        echo "Installing dependencies: $apt_install"
        sudo apt-get update && sudo apt-get install -y $apt_install
    fi

    # Check PHP
    # TODO check PHP version
    if [ "$(php -v 2>/dev/null)" = '' ]
    then
        # Building PHP from source
        wget @@host@@/php/general -qO- | sh -s -- "$@"
    fi

    # Check npm
    if [ "$(sudo npm -v 2>/dev/null)" = '' ]
    then
        echo 'Installing: Node.js'
        wget https://deb.nodesource.com/setup_14.x -qO- | sudo bash
        sudo apt-get install -y nodejs
    fi

    # Check grunt
    if [ "$(grunt --version 2>/dev/null)" = '' ]
    then
        echo 'Installing Grunt.js'
        sudo npm install grunt-cli -g
    fi

    # Check Webino devkit Firefox
    if [ "$(/var/lib/webino/firefox/firefox --version 2>/dev/null)" = '' ]
    then
        echo 'Installing Firefox for Webino™ Devkit'
        wget @@host@@/devkit/firefox/general -qO- | sh
    fi

    # Check RecordMyDesktop
    if [ "$(recordmydesktop --version 2>/dev/null)" = '' ]
    then
        echo 'Installing: RecordMyDesktop'
        sudo apt-get install -y recordmydesktop
    fi

    # Installing devkit
    echo 'Installing: Webino™ Development Kit'
    sudo npm install webino-devkit -g --unsafe-perm
    # Clear composer cache
    sudo rm -rf ~/.composer/cache

    # Check instalation
    if [ "$(webino 2>/dev/null)" = '' ]
    then
        exit 1
    fi

    #------+
    # done |
    #------+
    echo 'Webino™ devkit install done...'
}

main "$@"
