#!/bin/sh

# This is the Webino™ Devkit install script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino™ Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/devkit -qO- | sh
#
# Webino™ Devkit currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs Webino™ devkit


main () {
    echo -e "\nMachine setup for Webino™\n"

    #------+
    # init |
    #------+
    load ~lib
    load arguments "$@"

    #-------+
    # setup |
    #-------+
    load system/general
    load devkit/general

    #---------+
    # success |
    #---------+
    cat <<"EOF"

To get started:

  $ webino

Or see the docs at:

  https://github.com/webino/webino-devkit

EOF

    #------+
    # done |
    #------+
    setup_done
}

main "$@"
