#!/bin/bash

# This is the Webino Seed install script!
# Copyright (c) 2017 Webino, s. r. o. (http://webino.sk/)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to install Webino Devkit?
# Just open up your terminal and type
#
#    wget @@host@@/seed/certbot -qO- | sh
#
# Webino currently supports:
#   - Ubuntu 15.10 | 14.04 | 12.04 (wget 1.14)
#
# What this script does?
#   - It installs Let’s Encrypt certificate bot

main() {

    cd /opt
    git clone https://github.com/composer/satis.git --depth 1
    cd satis
    wget https://getcomposer.org/installer -qO- | php
    php composer.phar install
    mkdir -m 0777 /var/satis
}

main
