#!/bin/bash

# This is the Webino™ Travis support script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@

webino exec:stop-server
cat /tmp/selenium/port-44*.log
