#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs MySQL database

main() {
    #----------+
    # defaults |
    #----------+
    _mysql_client_user=www-data

    #----------+
    # get args |
    #----------+
    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        -mysql-client-user)
            _mysql_client_user=${argv[$n]}
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
