#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs MySQL database

main() {
    #---------+
    # install |
    #---------+
    echo -e "\nMySQL client..."
    install mysql-client

    #----------------------+
    # create client config |
    #----------------------+
    mysql_create_user "$_mysql_client_user"
}

main
