#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs MySQL database

main() {
    #-------------------------+
    # check already installed |
    #-------------------------+
    if [[ "$(whereis mysql)" == *"/mysql"* ]]; then
        echo 'MySQL client already installed...'

    #---------+
    # install |
    #---------+
    else
        echo 'Installing MySQL client...'
        apt-get install -y mysql-client
    fi

    #-----------+
    # configure |
    #-----------+
    echo 'Configuring MySQL client for user '$_mysql_client_user

    #---------------------+
    # resolve client home |
    #---------------------+
    local client_home=
    if [ "$(id $_mysql_client_user 2> /dev/null)" ]; then
        client_home=$(eval echo "~$_mysql_client_user")
    fi

    if [[ ! -d "$client_home" ]]; then
        echo 'MySQL client home directory not found!!!'
        return
    fi

    echo 'Resolved MySQL client home `'$client_home'`...'

    #------------------------------------+
    # check client config already exists |
    #------------------------------------+
    local config=$client_home'/.my.cnf'
    if [[ -f $config ]]; then
        echo 'MySQL client already configured...'
        return
    fi

    #---------------------------+
    # create client credentials |
    #---------------------------+
    if [ -z "${client_username-}" ]; then

    fi

    echo 'Generating MySQL client username...'
    local client_username=$(echo $(< /dev/urandom tr -dc a-z0-9 | head -c6))
    echo 'Generating MySQL password for username `'$client_username'`...'
    local client_password=$(echo $(< /dev/urandom tr -dc a-z0-9 | head -c12))

    #----------------------+
    # create client config |
    #----------------------+
    local data='@@host@@/mysql/~data'
    echo 'Creating MySQL client config...'

    echo "$(wget -qO- $data/home/example/.my.cnf | \
        sed s/'%USER%'/$client_username/ | \
        sed s/'%PASSWORD%'/$client_password/)" | \
        sudo tee $config > /dev/null

    sudo chown $_mysql_client_user:$_mysql_client_user $config
    sudo chmod 600 $config

    #--------------------------+
    # create mysql client user |
    #--------------------------+
    echo 'Creating MySQL client user...'
    sudo -i mysql -e "CREATE USER '$client_username'@'localhost' IDENTIFIED BY '$client_password';"
    sudo -i mysql -e "$(wget ${data}extra/mysql-grant-client.sql -qO- | sed s/'%USER%'/$client_username/g)"
}

main
