#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It installs MySQL database

main() {
    echo -e "\nMySQL install..."

    #-------+
    # setup |
    #-------+
    load mysql/arguments "$@"
    load mysql/utils
    load mysql/server
    load mysql/client

    #-----------------+
    # service restart |
    #-----------------+
    sudo service mysql stop > /dev/null 2>&1 && \
    sudo service mysql start > /dev/null 2>&1 &

    #--------------------------------+
    # server settings (dev|pub only) |
    #--------------------------------+
    if [[ $_env_dev || $_env_pub ]]; then
        load mysql/logwatch
    fi

    #------+
    # done |
    #------+
    echo 'MySQL install done...'
}

main "$@"
