#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/mysql -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs MySQL database

main() {
    #--------------------------+
    # check logwatch installed |
    #--------------------------+
    if [[ "$(whereis logwatch)" != *"/logwatch"* ]]; then
        echo 'Required logwatch installed!!!'
        return
    fi

    #--------------------------+
    # check already configured |
    #--------------------------+
    local file=/usr/share/logwatch/dist.conf/logfiles/mysql.conf
    if [[ -f $file ]]; then
        echo 'Logwatch for MySQL already configured...'
    fi

    #-------+
    # setup |
    #-------+
    local data='@@host@@/mysql/~data'
    echo 'Installing Logwatch for MySQL...'
    sudo wget $data$file -qO $file
}

main
