#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04

main() {
    #----------+
    # defaults |
    #----------+
    _apache_htaccess=

    #----------+
    # get args |
    #----------+
    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        -apache-htaccess)
            _apache_htaccess=1
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
