#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp/httpd
    
    #-------+
    # build |
    #-------+
    echo 'Building Apache...'

    # optional arguments
    local opt=''

    #----------------------------------+
    # disable autoindex (dev|pub only) |
    #----------------------------------+
    [[ ! $_env_local ]] && local opt='--disable-autoindex';

    sudo sh ./configure \
        --bindir=/usr/bin \
        --sbindir=/usr/sbin \
        --sysconfdir=/etc/apache2 \
        --with-included-apr \
        --with-perl \
        --with-ssl \
        --enable-ssl \
        --enable-rewrite \
        --enable-suexec \
        --enable-info \
        --enable-socache-shmbc \
        $opt

    make
    sudo make install
}

main
