#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    if [[ ! $_wbpo ]]; then
        return
    fi

    #-------------------+
    # configure support |
    #-------------------+
    local data='@@host@@/apache/~data'
    echo 'Configuring Apache to support WBPO...'

    #----------------------------+
    # WBPO™ support (optional) |
    #----------------------------+
    local file=/etc/apache2/conf.d/wbpo.conf
    root_file_wget $data$file $file
}

main
