#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds Apache from source

main() {
    #-------+
    # setup |
    #-------+
    local data='@@host@@/apache/~data'

    if [[ $(systemctl --version 2> /dev/null) ]]; then
        #-----------------+
        # systemd support |
        #-----------------+
        local file=/etc/systemd/system/httpd.service
        if [[ ! -f $file ]]; then
            echo 'Installing Apache systemd service...'
            root_file_wget $data$file $file
            sudo systemctl enable httpd.service > /dev/null 2>&1 &
        fi
    else
        #--------------------------+
        # upstart support (legacy) |
        #--------------------------+
        local file=/etc/init/httpd.conf
        if [[ ! -f $file ]]; then
            echo 'Installing Apache upstart script...'
            root_file_wget $data$file $file
            sudo initctl reload-configuration > /dev/null 2>&1 &
        fi
    fi
}

main
