#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp
    local lock=webino.apache.dependencies.lock

    #------------+
    # check lock |
    #------------+
    if [[ -f $lock ]]; then
        echo 'Dependencies for Apache build already installed...'
    fi

    #----------------------+
    # dependencies install |
    #----------------------+
    echo "Installing dependencies for Apache build..."

    sudo apt-get install -y \
        libexpat1-dev \
        libpcre3-dev \
        libssl-dev

    #------+
    # lock |
    #------+
    touch $lock
}

main
