#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    cd /tmp
    
    #----------------------+
    # dependencies install |
    #----------------------+
    echo 'Installing dependencies for Apache build...'

    install \
        libexpat1-dev \
        libpcre3-dev \
        libzip-dev \
        libssl-dev
}

main
