#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    echo -e "\nApache build...\n"

    #------+
    # init |
    #------+
    load apache/utils

    #----------------------+
    # remove pre-installed |
    #----------------------+
    load apache/purge

    #-------------------------+
    # check already installed |
    #-------------------------+
    if [[ $(whereis apachectl) == */apachectl* ]]; then
        echo 'Apache already built...'
        return
    fi
    
    #-----------------------------+
    # resolve latest 2.4 versions |
    #-----------------------------+
    local apache_version_latest=$(echo $(wget -qO- http://www.apache.org/dist/httpd/Announcement2.4.txt \
        | grep -a -Eom 1 'Server 2\.4\.[0-9]+ Released' | grep -a -Eom 1 '[0-9\.]+'))

    local apache_apr_version_latest=$(echo $(wget -qO- http://apr.apache.org/download.cgi \
        | grep -a -Eom 1 'APR 1\.[0-9]+\.[0-9]+ is the best' | grep -a -Eom 1 '[0-9\.]+'))

    local apache_apr_util_version_latest=$(echo $(wget -qO- http://apr.apache.org/download.cgi \
        | grep -a -Eom 1 'APR-util 1\.[0-9]+\.[0-9]+ is the best' | grep -a -Eom 1 '[0-9\.]+'))

    apache_version=${apache_version-$apache_version_latest}
    apache_apr_version=${apache_apr_version-$apache_apr_version_latest}
    apache_apr_util_version=${apache_apr_util_version-$apache_apr_util_version_latest}

    #--------------------------+
    # server name (local only) |
    #--------------------------+
    # TODO
    #apache_server_name='webino.'$([[ $USER == 'webino' ]] && echo 'local' || echo $USER)

    #---------------------------+
    # chown /srv (dev|pub only) |
    #---------------------------+
    # TODO remove?
    #[[ $_env_dev || $_env_pub ]] && sudo chown www-data:www-data /srv -R

    #----------------+
    # create www dir |
    #----------------+
    local dir=/var/www/public
    if [[ -d $dir ]]; then
        echo 'Public www directory already exists...'
    else
        echo 'Creating public www directory...'
        sudo mkdir -p $dir
        sudo chown www-data:www-data /var/www -R
    fi

    #---------+
    # install |
    #---------+
    echo 'Installing Apache '$apache_version
    load apache/dependencies
    load apache/download
    load apache/build
    load apache/configure
    load apache/daemon

    #--------------------+
    # web server restart |
    #--------------------+
    apache_restart || true

    #--------------------------------+
    # system settings (dev|pub only) |
    #--------------------------------+
    if [[ $_env_dev || $_env_pub ]]; then
        load apache/logwatch
        load apache/fail2ban
    fi

    #------+
    # done |
    #------+
    rm -rf /tmp/httpd
    echo 'Apache build done...'
}

main
