#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds Apache from source

main() {
    #------------------------------------------+
    # return early when Logwatch not installed |
    #------------------------------------------+
    [[ ! -d /usr/share/logwatch ]] && return

    #--------------------------+
    # check already configured |
    #--------------------------+
    local file=/usr/share/logwatch/dist.conf/logfiles/http.conf
    if [[ -f $file ]]; then
        echo 'Logwatch for Apache already installed...'
        return
    fi

    #-------+
    # setup |
    #-------+
    local data='@@host@@/apache/~data'
    echo 'Installing Logwatch for Apache...'
    root_file_wget $data$file $file

    local file=/usr/share/logwatch/dist.conf/logfiles/http-error.conf
    root_file_wget $data$file $file
}

main
