#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    #---------------------+
    # purge pre-installed |
    #---------------------+
    echo 'Removing pre-installed Apache...'
    uninstall apache*
    sudo rm -rf /etc/apache2 /usr/local/apache2 /var/www/html
}

main
