#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds Apache from source

main() {
    #-----------------+
    # check installed |
    #-----------------+
    if [[ ! $(apt list --installed 2>/dev/null | grep -o apache2) ]]; then
        # not installed, return early
        return
    fi

    #-------+
    # purge |
    #-------+
    echo 'Removing pre-installed Apache...'
    sudo apt-get purge -y apache*
    sudo apt-get autoremove -y
    sudo rm -rf /etc/apache2
    sudo rm -rf /usr/local/apache2
    sudo rm -rf /var/www/html
}

main
