#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/apache -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds Apache from source

#--------------------+
# Web server restart |
#--------------------+
apache_restart()
{
    echo 'Restarting web server...'
    $(sleep 3 && sudo apachectl restart > /dev/null 2>&1) &
    return
}

#-------------------+
# Web server reload |
#-------------------+
apache_reload()
{
    echo 'Reloading web server...'
    $(sleep 3 && sudo apachectl graceful > /dev/null 2>&1) &
    return
}
