#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 14.04

main() {
    #----------+
    # defaults |
    #----------+
    _no_interaction=
    _env_local=1
    _env_dev=
    _env_pub=
    _update=
    _clean=
    _admin_mail=

    #----------+
    # get args |
    #----------+
    argv=("$@")
    n=0
    for i in "$@"
    do
    argv[$n]=$i
    n=$((n + 1))
    case $i in
        --no-interaction|-n) # non interactive
            _no_interaction=1
            shift
        ;;
        --local)
            _env_local=1
            _env_dev=
            _env_pub=
            shift
        ;;
        --dev)
            _env_dev=1
            _env_local=
            _env_pub=
            shift
        ;;
        --pub)
            _env_pub=1
            _env_dev=
            _env_local=
            shift
        ;;
        --update)
            _update=1
            shift
        ;;
        --clean)
            _clean=1
            shift
        ;;
        --admin-mail)
            _admin_mail=${argv[$n]}
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "$@"
