#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04

main() {
    #----------+
    # defaults |
    #----------+
    _no_interaction=
    _no_webino=
    _wbpo=
    _env_local=1
    _env_dev=
    _env_pub=
    _update=
    _clean=
    _verbose=
    _admin_email=

    #----------+
    # get args |
    #----------+
    argv=("$@")
    n=0
    for i in "$@"
    do
    argv[$n]=$i
    n=$((n + 1))
    case $i in
        -no-interaction|-n)
            _no_interaction=1
            shift
        ;;
        -no-webino)
            _no_webino=1
            shift
        ;;
        -wbpo)
            _no_webino=1
            _wbpo=1
            shift
        ;;
        -admin-email)
            _admin_email=${argv[$n]}
            shift
            shift
        ;;
        -local)
            _env_local=1
            _env_dev=
            _env_pub=
            shift
        ;;
        -dev)
            _env_dev=1
            _env_local=
            _env_pub=
            shift
        ;;
        -pub)
            _env_pub=1
            _env_dev=
            _env_local=
            shift
        ;;
        -update)
            _update=1
            shift
        ;;
        -clean)
            _clean=1
            shift
        -v)
            _verbose=1
            shift
        -vv)
            _verbose=2
            shift
        -vvv)
            _verbose=3
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "$@"
