#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@ -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino.tmp
    source /tmp/webino.tmp && rm /tmp/webino.tmp
}

main() {
    echo -e "\nMachine setup for Webino™...\n"

    load lib/trap
    load lib/spinner
    load arguments "$@"

    # Install
    load os/general
    load sw/apache
    load sw/mysql
    load sw/php
    load sw/devkit

    echo -e "\nSuccess...\n"
}

main "$@"
