#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext

    #---------+
    # install |
    #---------+
    if ls /usr/local/lib/php/extensions/no-debug-zts-*/apcu.so &>/dev/null; then
        echo 'APCu already installed...'
    else
        echo 'Installing APCu...'

        if [ ! -d apcu ]; then
            echo 'Downloading APCu...'
            wget http://pecl.php.net/get/apcu-5.1.18.tgz \
                -O apcu.tgz && tar xvf apcu.tgz & spinner $! && mv apcu-5.1.18 apcu && rm apcu.tgz 2>&1
        else
            echo 'APCu already downloaded...'
        fi
        
        cd apcu
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}
    local file=/php.ini
    if [[ ! $(grep apcu.so $etc$file) ]]; then
        echo 'Enabling PHP APCu module...'
        echo 'extension=apcu.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
