#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04

main() {
    #----------+
    # defaults |
    #----------+
    _php_version=
    _php_prefix=
    _php_short_tags=
    _php_memcached=
    _php_fpm=

    #----------+
    # get args |
    #----------+
    n=0
    for i in "$@"
    do
    n=$((n + 1))
    case $i in
        -php)
            _php_version=${argv[$n]}
            shift
            shift
        ;;
        -php-prefix)
            _php_prefix=${argv[$n]}
            shift
            shift
        ;;
        -php-short-tags)
            _php_short_tags=1
            shift
            shift
        ;;
        -php-memcached)
            _php_memcached=1
            shift
            shift
        ;;
        -php-fpm)
            _php_fpm=1
            shift
            shift
        ;;
        *)
            # unknown option
        ;;
    esac
    done
}

main "${argv[@]}"
