#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds PHP from source

main() {
    #------------+
    # IMAP build |
    #------------+
    #cd /tmp/imap-2007f
    #if [[ -d /usr/local/imap-2007f ]]; then
    #    echo 'IMAP already built...'
    #else
    #    echo 'Building IMAP... TODO'
        #make slx SSLINCLUDE=/usr/include/openssl EXTRACFLAGS=-fPIC
        #mkdir lib && mkdir include
        #cp c-client/*.c lib
        #cp c-client/*.h include
        #cp c-client/c-client.a lib/libc-client.a
        #sudo cp . /usr/local/imap-2007f -R
    #fi

    #if php -v &>/dev/null; then
    #    echo 'PHP already built...'
    #    return
    #fi

    #------------------+
    # PHP build config |
    #------------------+
    local prefix='/'${_php_prefix:-'php'}
    local php_cfg="--with-config-file-path=/etc$prefix \
            --with-config-file-scan-dir=/etc$prefix/conf.d:/etc$prefix/local.d \
            --enable-cli \
            --enable-calendar \
            --enable-pcntl \
            --enable-soap \
            --enable-bcmath \
            --enable-exif \
            --enable-mbstring \
            --with-zlib \
            --with-zlib-dir \
            --with-iconv \
            --with-pdo-mysql \
            --with-mysqli \
            --with-gettext \
            --with-mhash \
            --with-pspell \
            --with-libedit \
            --with-kerberos \
            --with-imap \
            --with-imap-ssl \
            --with-xsl=/usr \
            --with-curl=/usr \
            --without-pear \
            --without-readline"

    #---------------------------+
    # Intl support for PHP>=5.4 |
    #---------------------------+
    sudo dpkg --compare-versions "$_php_version" 'lt' '5.4' || {
       echo 'With INTL support...'
       php_cfg+=' --enable-intl'
    }

    #--------------+
    # For PHP>=7.0 |
    #--------------+
    sudo dpkg --compare-versions "$_php_version" 'lt' '7.0' && {
    
        echo 'Without PHP7 support (legacy)...'
        php_cfg+=" --with-mcrypt \
                   --enable-gd-native-ttf"
    } || {
    
       echo 'With PHP7 support...'
       php_cfg+=" --enable-ftp \
                  --enable-sockets"

       #-----------------+
       # OPENSSL support |
       #-----------------+
       if [[ $_php_openssl ]]; then
           echo 'With OPENSSL support...'
           php_cfg+=' --with-openssl \
                      --with-openssl-dir=/usr'
       fi

       #--------------+
       # For PHP>=7.4 |
       #--------------+
       sudo dpkg --compare-versions "$_php_version" 'lt' '7.4' && {

           echo 'Without PHP7.4 support (legacy)...'
           php_cfg+=" --enable-zip \
                      --enable-wddx \
                      --with-libzip \
                      --with-freetype-dir \
                      --with-jpeg-dir=/usr/lib \
                      --with-gd"
       } || {

          echo 'With PHP7.4 support...'
          install libsqlite3-dev \
                  libonig-dev
                 
          php_cfg+=" --with-zip \
                     --with-freetype \
                     --with-jpeg=/usr/lib \
                     --enable-gd"
       }
    }

    #---------------------+
    # path prefix support |
    #---------------------+
    if [[ $_php_prefix ]]; then
        echo 'With prefix: '$prefix
        php_cfg+=' --prefix=/opt'$prefix

    #----------------+
    # Apache support |
    #----------------+
    elif [[ $_php_apache ]]; then
        echo 'With Apache...'
        php_cfg+=' --with-apxs2=/usr/bin/apxs'
    fi

    #-----------------+
    # PHP-FPM support |
    #-----------------+
    if [[ $_php_fpm ]]; then
        echo 'With PHP-FPM support...'
        php_cfg+=' --enable-fpm'
    fi

    #-----------------+
    # SQLite support |
    #-----------------+
    if [[ ! $_php_sqlite ]]; then
        echo 'Without SQLite support...'
        php_cfg+=' --without-sqlite3'
    fi

    #-----------+
    # PHP build |
    #-----------+
    cd /tmp/php || return
    echo 'Building PHP...'
    echo 'with config:'
    echo $php_cfg;
    echo

    ./buildconf --force
    ./configure $php_cfg
    make
    sudo make install
}

main
