#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    #------------+
    # IMAP build |
    #------------+
    cd /tmp/imap-2007f
    local lock=built.lock

    if [[ -f $lock ]]; then
        echo 'IMAP already built...'
    else
        echo 'Building IMAP...'
        make slx SSLINCLUDE=/usr/include/openssl EXTRACFLAGS=-fPIC
        mkdir lib && mkdir include
        cp c-client/*.c lib
        cp c-client/*.h include
        cp c-client/c-client.a lib/libc-client.a
        sudo cp . /usr/local/imap-2007f -R
        touch $lock
    fi

    #------------------+
    # PHP build config |
    #------------------+
    local prefix='/'${_php_prefix:-'php'}
    local php_cfg="--with-config-file-path=/etc$prefix \
            --with-config-file-scan-dir=/etc$prefix/conf.d:/etc$prefix/local.d \
            --enable-cli \
            --enable-calendar \
            --enable-pcntl \
            --enable-soap \
            --enable-zip \
            --enable-bcmath \
            --enable-exif \
            --enable-gd-native-ttf \
            --enable-mbstring \
            --with-gd \
            --with-zlib \
            --with-zlib-dir \
            --with-iconv \
            --with-pdo-mysql \
            --with-gettext \
            --with-mhash \
            --with-pspell \
            --with-libedit \
            --with-kerberos \
            --with-imap \
            --with-imap-ssl \
            --with-xsl=/usr \
            --with-curl=/usr \
            --with-jpeg-dir=/usr/lib \
            --with-freetype-dir \
            --without-pear \
            --without-readline"

    # TODO pear hacked, remove?
    #--with-pear \

    #---------------------------+
    # Intl support for PHP>=5.4 |
    #---------------------------+
    sudo dpkg --compare-versions "$_php_version" 'lt' '5.4' || {
       echo 'With INTL support...'
       php_cfg+=' --enable-intl'
    }

    #--------------+
    # For PHP>=7.0 |
    #--------------+
    sudo dpkg --compare-versions "$_php_version" 'lt' '7.0' && {

        echo 'Without PHP7 support (legacy)...'
        php_cfg+=" --with-mcrypt \
                   --with-mysqli"
    } || {

       echo 'With PHP7 support...'
       php_cfg+=" --enable-ftp \
                  --enable-wddx \
                  --enable-sockets \
                  --with-openssl \
                  --with-openssl-dir=/usr"
    }

    #---------------------+
    # path prefix support |
    #---------------------+
    if [[ $_php_prefix ]]; then
        echo 'With prefix: '$prefix
        php_cfg+=' --prefix=/opt'$prefix

    #----------------+
    # Apache support |
    #----------------+
    elif [[ $_php_apache ]]; then
        echo 'With Apache...'
        php_cfg+=' --with-apxs2=/usr/bin/apxs'
    fi

    #-----------------+
    # PHP-FPM support |
    #-----------------+
    if [[ $_php_fpm ]]; then
        echo 'With PHP-FPM support...'
        php_cfg+=' --enable-fpm'
    fi

    #-----------+
    # PHP build |
    #-----------+
    cd /tmp/php
    local lock=built.lock
    if [[ -f $lock ]]; then
        echo 'PHP already built...'
    else
        echo 'Building PHP...'
        echo 'with config:'
        echo $php_cfg;
        echo

        ./buildconf --force
        ./configure $php_cfg
        make
        sudo make install
        touch $lock
    fi
}

main
