#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds PHP from source

bison_install() {
    echo 'Installing bison...'
    sudo apt-get purge -y bison
    sudo wget http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb
    sudo wget http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb
    sudo dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb
    sudo dpkg -i bison_2.7.1.dfsg-1_amd64.deb
}

main() {
    cd /tmp
    
    #----------------------+
    # dependencies install |
    #----------------------+
    echo "Installing dependencies for PHP build..."
    install \
        libc-client2007e \
        libcurl4-openssl-dev \
        libpspell-dev \
        libzip-dev \
        libicu-dev \
        libedit-dev \
        libfreetype6-dev \
        libmagickwand-dev \
        libmcrypt-dev \
        libxslt1-dev \
        libc-client-dev \
        libkrb5-dev \
        bison

    #-------+
    # bison |
    #-------+
    if [[ $(whereis bison) == */bison* ]]; then
        echo 'Checking installed bison version...'
        sudo dpkg --compare-versions $(bison -V | grep -o [0-9]\.[0-9] | head -1) gt 2.3 || bison_install
    else
        bison_install
    fi

    # TODO PHP 5.3.29 legacy support
    # TODO apt-get install autoconf2.13
    # TODO export PHP_AUTOCONF=autoconf2.13
}

main
