#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-@@year@@ Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 / Ubuntu 18.04
#
# What this script does?
#   - It builds PHP from source

main() {
    #------------------------------------------+
    # return early when File2ban not installed |
    #------------------------------------------+
    local dir=/etc/fail2ban/jail.d
    [[ ! -d $dir ]] && return

    #--------------------------+
    # check already configured |
    #--------------------------+
    local file=$dir/php.conf
    if [[ -f $file ]]; then
        echo 'Fail2ban for PHP already configured...'
        return
    fi

    #-------+
    # setup |
    #-------+
    local data='@@host@@/php/~data'
    echo 'Installing Fail2ban for PHP...'
    root_file_wget $data$file $file

    #-----------------+
    # service restart |
    #-----------------+
    sudo service fail2ban restart > /dev/null 2>&1 &
}

main
