#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php
    local lock=imagick.lock

    #---------+
    # install |
    #---------+
    if [[ -f $lock ]]; then
        echo 'ImageMagick already installed...'
    else
        echo 'Installing ImageMagick...'
        # non-interactive
        printf '\n' | sudo pecl install -f imagick
        touch $lock
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}

    local file=/php.ini
    if [[ ! $(grep imagick.so $etc$file) ]]; then
        echo 'Enabling PHP Imagick module...'
        echo 'extension=imagick.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi

    #---------------+
    # configure CLI |
    #---------------+
    local file=/php-cli.ini
    if [[ ! $(grep  $etc$file) ]]; then
        echo 'Enabling PHP-CLI Imagick module...'
        echo 'extension=imagick.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
