#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext
    
    #---------+
    # install |
    #---------+
    if ls /usr/local/lib/php/extensions/no-debug-zts-*/imagick.so &>/dev/null; then
        echo 'ImageMagick already installed...'
    else
        echo 'Installing ImageMagick...'
        
        if [ ! -d imagick  ]; then
            echo 'Downloading ImageMagick...'
            wget http://pecl.php.net/get/imagick-3.4.4.tgz \
                -O imagick.tgz && tar xvf imagick.tgz & spinner $! && mv imagick-3.4.4 imagick && rm imagick.tgz 2>&1
        else
            echo 'ImageMagick already downloaded...'
        fi
            
        cd imagick
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}

    local file=/php.ini
    if [[ ! $(grep imagick.so $etc$file) ]]; then
        echo 'Enabling PHP Imagick module...'
        echo 'extension=imagick.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi

    #---------------+
    # configure CLI |
    #---------------+
    local file=/php-cli.ini
    if [[ ! $(grep imagick.so $etc$file) ]]; then
        echo 'Enabling PHP-CLI Imagick module...'
        echo 'extension=imagick.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
