#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    #---------------------------------------------+
    # return early when Logwatch is not installed |
    #---------------------------------------------+
    [[ ! -d /usr/share/logwatch ]] && return

    local data='@@host@@/php/~data'
    local file=/usr/share/logwatch/dist.conf/logfiles/php.conf

    #-------------------------+
    # check already installed |
    #-------------------------+
    if [[ -f $file ]]; then
        echo 'Logwatch for PHP already installed...'
        return
    fi

    #---------+
    # install |
    #---------+
    echo 'Installing Logwatch for PHP...'
    sudo wget $data$file -qO $file
}

main
