#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php
    local lock=mailparse.lock

    #---------+
    # install |
    #---------+
    if [[ -f $lock ]]; then
        echo 'Mailparse already installed...'
    else
        echo 'Installing Mailparse...'
        # depends on PHP version
        local mailparse_version=$(php -r "echo (-1 === version_compare('$_php_version', '7.0.0') ? '2.1.6' : '3.0.2');")
        echo 'Version: '$mailparse_version
        # non-interactive
        printf '\n' | sudo pecl install -f 'mailparse-'$mailparse_version
        touch $lock
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}

    local file=/php.ini
    if [[ ! $(grep mailparse.so $etc$file) ]]; then
        echo 'Enabling PHP Mailparse module...'
        echo 'extension=mailparse.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi

    #---------------+
    # configure CLI |
    #---------------+
    local file=/php-cli.ini
    if [[ ! $(grep mailparse.so $etc$file) ]]; then
        echo 'Enabling PHP-CLI Mailparse module...'
        echo 'extension=mailparse.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
