#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext
    
    #---------+
    # install |
    #---------+
    if test ls /usr/local/lib/php/extensions/no-debug-zts-*/mailparse.so &>/dev/null; then
        echo 'Mailparse already installed...'
    else
        echo 'Installing Mailparse...'
        
        # depends on PHP version
        local mailparse_version=$(php -r "echo (-1 === version_compare('$_php_version', '7.0.0') ? '2.1.6' : '3.0.2');")
        echo 'Version: '$mailparse_version
        
        if [ ! -d mailparse  ]; then
            echo 'Downloading Mailparse...'
            wget http://pecl.php.net/get/mailparse-$mailparse_version.tgz \
                -O mailparse.tgz && tar xvf mailparse.tgz & spinner $! && mv mailparse-$mailparse_version mailparse && rm mailparse.tgz 2>&1
        else
            echo 'Mailparse already downloaded...'
        fi
        
        cd mailparse
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}

    local file=/php.ini
    if [[ ! $(grep mailparse.so $etc$file) ]]; then
        echo 'Enabling PHP Mailparse module...'
        echo 'extension=mailparse.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi

    #---------------+
    # configure CLI |
    #---------------+
    local file=/php-cli.ini
    if [[ ! $(grep mailparse.so $etc$file) ]]; then
        echo 'Enabling PHP-CLI Mailparse module...'
        echo 'extension=mailparse.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
