#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext

    #---------+
    # install |
    #---------+
    if ls /usr/local/lib/php/extensions/no-debug-zts-*/memcached.so &>/dev/null; then
        echo 'Memcached already installed...'
    else
        echo 'Installing Memcached...'

        if [ ! -d memcached ]; then
            echo 'Downloading Memcached...'
            wget http://pecl.php.net/get/memcached-3.1.3.tgz \
                -O memcached.tgz && tar xvf memcached.tgz & spinner $! && mv memcached-3.1.3 memcached && rm memcached.tgz 2>&1
        else
            echo 'Memcached already downloaded...'
        fi
        
        install libmemcached-dev
        cd memcached
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}
    local file=/php.ini
    if [[ ! $(grep memcached.so $etc$file) ]]; then
        echo 'Enabling PHP Memcached module...'
        echo 'extension=memcached.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
