#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext/opcache

    #---------+
    # install |
    #---------+
    if ls /usr/local/lib/php/extensions/no-debug-zts-*/opcache.so &>/dev/null; then
        echo 'Zend OPCache already installed...'
    else
        echo 'Installing Zend OPCache...'
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}
    local file=/php.ini
    if [[ ! $(grep opcache.so $etc$file) ]]; then
        echo 'Enabling PHP Zend OPCache module...'
        echo 'zend_extension=opcache.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
