#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php
    local lock=profiler.lock

    if [[ -f $lock ]]; then
        echo 'Profiler already installed...'
    else
        echo 'Installing Profiler...'
        # TODO use blackfire
        touch $lock
    fi

    # TODO add profiler extension to php.ini
}

main
