#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

load() {
    #-------------------------+
    # load remote bash source |
    #-------------------------+
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino
}

main() {
    echo -e "\nMachine setup for Webino™ (PHP build)...\n"

    #------+
    # init |
    #------+
    load ~lib
    load arguments "$@"

    #-------+
    # setup |
    #-------+
    load system/general
    # with Apache (optional)
    [[ $@ =~ --with-apache( |$) ]] load apache/general
    # with MySQL (optional)
    [[ $@ =~ --with-mysql( |$) ]] load mysql/general
    load php/general
}

main "$@"
