#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

#-----------------+
# PHP-FPM restart |
#-----------------+
php_fpm_restart()
{
    echo 'Restarting PHP_FPM...'
    $(sleep 3 && sudo /usr/sbin/php-fpm stop; sleep 1 && sudo /usr/sbin/php-fpm start > /dev/null 2>&1) &
}

#--------------+
# PHP-FPM stop |
#--------------+
php_fpm_stop()
{
    echo 'Stopping PHP_FPM...'
    $(sleep 3 && sudo /usr/sbin/php-fpm stop > /dev/null 2>&1) &
}
