#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2019 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/php -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It builds PHP from source

main() {
    cd /tmp/php/ext
    
    #---------+
    # install |
    #---------+
    if ls /usr/local/lib/php/extensions/no-debug-zts-*/xdebug.so &>/dev/null; then
        echo 'Xdebug already installed...'
    else
        echo 'Installing Xdebug...'
        
        if [ ! -d xdebug ]; then
            echo 'Downloading Xdebug...'
            wget http://pecl.php.net/get/xdebug-2.6.1.tgz \
                -O xdebug.tgz && tar xvf xdebug.tgz & spinner $! && mv xdebug-2.6.1 xdebug && rm xdebug.tgz 2>&1
        else
            echo 'Xdebug already downloaded...'
        fi
        
        cd xdebug
        phpize
        ./configure
        make
        sudo make install
    fi

    #-----------+
    # configure |
    #-----------+
    local etc='/etc/'${_php_prefix:-'php'}
    local file=/php.ini
    if [[ ! $(grep xdebug.so $etc$file) ]]; then
        echo 'Enabling PHP Xdebug module...'
        echo 'zend_extension=xdebug.so' | cat - $etc$file | sudo tee $etc$file > /dev/null
    fi
}

main
