#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/dev -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04 | 15.10 | 14.04
#
# What this script does?
#   - It installs dev server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino.tmp
    source /tmp/webino.tmp
}

main() {
    # lock check
    local lock=/tmp/webino.dev.lock
    if [[ -f $lock ]]; then
        echo 'Webino™ (Dev server) already configured...'
    fi

    # setup
    echo -e "\nMachine setup for Webino™ (Dev server)...\n"
    local data='@@host@@/data/'

    load lib/trap
    load lib/spinner
    load arguments "$@"
    load dev/general

    # dev vhost setup
    sudo mkdir -p /srv/dev/pub
    sudo mkdir -p /srv/dev/log
    sudo chown www-data:www-data -R /srv/dev

    # vhost conf setup
    local file=/etc/php/fpm/pool.d/dev-srv.conf
    [[ -f $file ]] || sudo wget -qO $file $data$file

    # TODO
    # adding SFTP access for dev group
    sudo groupadd sftp-only
    # enable SFTP for sftp-only
    local is_ssh_sftp_allowed=$(grep 'AllowGroups .* sftp-only' /etc/ssh/sshd_config)
    if [[ -z "$is_ssh_sftp_allowed" ]]; then
        sudo sed -i -E 's/AllowGroups (.+)/AllowGroups \1 sftp-only/' /etc/ssh/sshd_config
        # TODO setup ssh sftp-only config
    fi

    sudo mkdir /sftp

    # TODO decouple to script call
    #load dev/user "$@"

    touch $lock
    echo -e "\nWebino™ (Dev server) configuration success...\n"
}

main "$@"
