#!/bin/bash

# This is the Webino™ setup script!
# Copyright (c) 2015-2018 Webino, s.r.o. (http://webino.sk)
# Version: @@version@@
#
# Are you looking at this in your web browser, and would like to get Webino™?
# Just open up your terminal and type:
#
#    wget @@host@@/media -qO- | sh
#
# Webino™ currently supports:
#   - Ubuntu 16.04
#
# What this script does?
#   - It installs media server

load() {
    # Load remote bash source
    wget @@host@@/$1 -qO /tmp/webino
    source /tmp/webino; rm webino
}

main() {
    echo -e "\nMachine setup for Webino™ (Media server)...\n"

    load lib/trap
    load lib/spinner
    load arguments "$@"

    # Force production environment
    _env_local=
    _env_dev=
    _env_pub=1

    # Install
    load os/general
    load sw/apache
    load sw/php
    load sw/git-srv
    load sw/satis

    echo -e "\nSuccess...\n"
}

main "$@"
